/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBDECAYNEW_h
#define ROOBDECAYNEW_h

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsCategory.h"
#include "RooCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "RooEffProd.h"
#include "TH1D.h"
#include "RooBDecaySpecial.h"

class RooBDecayNew : public RooAbsPdf {
public:

  /// flags
  
  RooBDecayNew() {} ; 
  RooBDecayNew(const char *name, const char *title,
                            RooBDecaySpecial& _dec1,
                            RooBDecaySpecial& _dec2);
  RooBDecayNew(const RooBDecayNew& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBDecayNew(*this,newname); }
  inline virtual ~RooBDecayNew() { }
  virtual Bool_t forceAnalyticalInt(const RooAbsArg& /*dep*/) const { 
    return kTRUE ; 
  }
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
  //virtual Double_t getValV(const RooArgSet* set=0) const ;

  Int_t getGenerator(RooArgSet& directVars, RooArgSet &generateVars, Bool_t staticInitOK=kTRUE) const;
  void generateEvent(Int_t code);

protected:

   RooRealProxy dec1;
   RooRealProxy dec2;
   Double_t evaluate() const;
   //Int_t qj;

private:

  ClassDef(RooBDecayNew,1) // Your description goes here...
};
 
#endif
