/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBDECAYNEWGEN_h
#define ROOBDECAYNEWGEN_h

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsCategory.h"
#include "RooCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "RooEffProdSpecial.h"
#include "TH1D.h"
#include "RooBDecaySpecial.h"

class RooBDecayNewGen : public RooAbsPdf {
public:

  /// flags
  
  RooBDecayNewGen() {} ; 
  RooBDecayNewGen(const char *name, const char *title,
                            RooEffProdSpecial& _dec1,
                            RooEffProdSpecial& _dec2);
  RooBDecayNewGen(const RooBDecayNewGen& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBDecayNewGen(*this,newname); }
  inline virtual ~RooBDecayNewGen() { }
  virtual Bool_t forceAnalyticalInt(const RooAbsArg& /*dep*/) const { 
    return kTRUE ; 
  }
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
  //virtual Double_t getValV(const RooArgSet* set=0) const ;

protected:

   RooRealProxy dec1;
   RooRealProxy dec2;
   Double_t evaluate() const;
   //Int_t qj;

private:

  ClassDef(RooBDecayNewGen,1) // Your description goes here...
};
 
#endif
