/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 
#ifndef ROOBDECAYNEWGEN_cxx
#define ROOBDECAYNEWGEN_cxx

#include "Riostream.h" 

#include "RooBDecayNewGen.h" 
#include "RooExponential.h"
#include "RooEffProdSpecial.h"
#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "Math/SpecFuncMathMore.h"
#include "Math/SpecFuncMathCore.h"
#include "RooBDecaySpecial.h"

ClassImp(RooBDecayNewGen) 

 RooBDecayNewGen::RooBDecayNewGen(const char *name, const char *title,
                            RooEffProdSpecial& _dec1,
                            RooEffProdSpecial& _dec2) :
   RooAbsPdf(name,title),
   dec1("dec1","dec1",this,_dec1),
   dec2("dec2","dec2",this,_dec2)
 {
 } 


 RooBDecayNewGen::RooBDecayNewGen(const RooBDecayNewGen& other, const char* name) :  
   RooAbsPdf(other,name),
   dec1("dec1",this,other.dec1),
   dec2("dec2",this,other.dec2)
 { 
 } 



 Double_t RooBDecayNewGen::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

   Double_t retVal = ((RooAbsPdf *) dec1.absArg())->getVal(0) + 
                     ((RooAbsPdf *) dec2.absArg())->getVal(0);


   //printf("Evaluate T=%g U=%g tot=%g\n",
   //  ((RooAbsPdf *) dec1.absArg())->getVal(0),
   //  ((RooAbsPdf *) dec2.absArg())->getVal(0),
   //  retVal);
   if(retVal < 0) { retVal = 1e-12; }//printf("FUNZIONE NEGATIVA ##################################\n"); }
   return retVal;

 } 

 Int_t RooBDecayNewGen::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   Int_t codeDec1 = 0, codeDec2 = 0;
   //RooArgSet QVars = RooArgSet();
   //RooArgSet tmpVars = RooArgSet();
   //matchArgs(allVars,QVars,tmpVars);

   codeDec1   = dec1.arg().getAnalyticalIntegralWN(allVars, analVars, NULL, rangeName);
   codeDec2   = dec2.arg().getAnalyticalIntegralWN(allVars, analVars, NULL, rangeName);

   //printf("ALLVARS GETANALYTICALINTEGRAL ROOBDECAYNEW\n");
   //if(allVars.getSize()>0) allVars.Print("v");

   //printf("ANALVARS GETANALYTICALINTEGRAL ROOBDECAYNEW\n");
   //if(analVars.getSize()>0) analVars.Print("v");

   if(codeDec1!=codeDec2) printf("COGLIONE BDECAY\n"), exit(1);
   //retCode = codeDec1 == codeDec2 ? codeDec1 : 0;//printf("COGLIONE\n"), exit(1);
   //printf("CODE GETANALYTICALINTEGRAL ROOBDECAYNEW %d\n", codeDec1);
   return codeDec1;

 } 


 Double_t RooBDecayNewGen::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   Double_t retVal = 0;
   if (code!=0) {

     retVal = dec1.arg().analyticalIntegralWN(code,NULL,rangeName) +
              dec2.arg().analyticalIntegralWN(code,NULL,rangeName);

     //printf("ANALYTICALINTEGRAL ROOBDECAYNEW code=%d T=%g U=%g tot=%g\n",code,
     //       dec1.arg().analyticalIntegralWN(code,NULL,rangeName),
     //       dec2.arg().analyticalIntegralWN(code,NULL,rangeName),
     //       retVal);

   }

   return retVal;

 } 
/*
Double_t RooBDecayNewGen::getValV(const RooArgSet* nset) const
{
if (!nset) {
    RooArgSet* tmp = _normSet ;
    _normSet = 0 ;
    Double_t val = evaluate() ;
    _normSet = tmp ;
    //Bool_t error = traceEvalPdf(val) ;

    //if (error) {
     //printf("ROOBDECAYSPECIAL GETVALV: return 0 col cazzo\n");
     //return 0 ;
    //}
    return val ;
  }
  Bool_t nsetChanged(kFALSE) ;
  if (nset!=_normSet || _norm==0) {
    nsetChanged = syncNormalization(nset) ;
  }


  if (isValueDirty() || nsetChanged || _norm->isValueDirty()) {
    Double_t rawVal = evaluate() ;
    //Bool_t error = traceEvalPdf(rawVal) ; // Error checking and printing
    Double_t normVal(_norm->getVal()) ;

    //if (normVal<=0.) {
    //  error=kTRUE ;
    //  logEvalError("p.d.f normalization integral is zero or negative") ;
    //}

    //if (error) {
    //  printf("ROOBDECAYSPECIAL GETVALV 2: return 0 col cazzo\n");   
      //_value = 0 ;
      _value = rawVal / normVal ;
    //} else {
    //  _value = rawVal / normVal ;
    //}

    clearValueAndShapeDirty() ; //setValueDirty(kFALSE) ;
  }

  return _value ;
}

*/
#endif