/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 
#ifndef ROOTIMEPDFBKG_cxx
#define ROOTIMEPDFBKG_cxx

#include "Riostream.h" 

//#include "RooTimePdfBkg.h" 
#include "RooCubicSplinePdf.h" 
#include "RooExponential.h"
#include "RooEffProd.h"
#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "Math/SpecFuncMathMore.h"
#include "Math/SpecFuncMathCore.h"

ClassImp(RooTimePdfBkg) 

 RooTimePdfBkg::RooTimePdfBkg(const char *name, const char *title,
                            RooAbsCategory& _q,
                            RooAbsReal& _time,
                            RooAbsReal& _c1T,
                            RooAbsReal& _fracT,
                            RooAbsReal& _alpha1T,
                            RooAbsReal& _alpha2T,
                            RooAbsReal& _c1U,
                            RooAbsReal& _fracU,
                            RooAbsReal& _alpha1U,
                            RooAbsReal& _alpha2U) :
   RooAbsPdf(name,title),
   q("q","q",this,_q),
   time("time","time",this,_time),
   c1T("c1T","c1T",this,_c1T),
   fracT("fracT","fracT",this,_fracT),
   alpha1T("alpha1T","alpha1T",this,_alpha1T),
   alpha2T("alpha2T","alpha2T",this,_alpha2T),
   c1U("c1U","c1U",this,_c1U),
   fracU("fracU","fracU",this,_fracU),
   alpha1U("alpha1U","alpha1U",this,_alpha1U),
   alpha2U("alpha2U","alpha2U",this,_alpha2U)   
 {
 } 


 RooTimePdfBkg::RooTimePdfBkg(const RooTimePdfBkg& other, const char* name) :  
   RooAbsPdf(other,name),
   q("q",this,other.q),
   time("time",this,other.time),
   c1T("c1T",this,other.c1T),
   fracT("fracT",this,other.fracT),
   alpha1T("alpha1T",this,other.alpha1T),
   alpha2T("alpha2T",this,other.alpha2T),
   c1U("c1U",this,other.c1U),
   fracU("fracU",this,other.fracU),
   alpha1U("alpha1U",this,other.alpha1U),
   alpha2U("alpha2U",this,other.alpha2U)
 { 
 } 



 Double_t RooTimePdfBkg::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

  Double_t expT = fracT*alpha1T*exp(alpha1T*time)/(exp(alpha1T*time.max())-exp(alpha1T*time.min()))+
                  (1-fracT)*alpha2T*exp(alpha2T*time)/(exp(alpha2T*time.max())-exp(alpha2T*time.min()));
  Double_t expU = fracU*alpha1U*exp(alpha1U*time)/(exp(alpha1U*time.max())-exp(alpha1U*time.min()))+
                  (1-fracU)*alpha2U*exp(alpha2U*time)/(exp(alpha2U*time.max())-exp(alpha2U*time.min()));

//  Double_t accT = (1+erf(c1T*time+c2T));
//  Double_t accU = (1+erf(c1U*time+c2U));

//  Double_t accT = (1+erf(c1T-c1T*time));
//  Double_t accU = (1+erf(c1U-c1U*time));

  Double_t accT = (1+tanh(c1T-c1T*time));
  Double_t accU = (1+tanh(c1U-c1U*time));

  Double_t retVal = (q==0) ? accU*expU :
                             accT*expT;


  Int_t iq = q;
  Double_t dtime = time;
  Double_t dtimeMax = time.max();
  Double_t dtimeMin = time.min();
  //printf("EVALUATE %d %g %g %g %g\n",iq,dtime,dtimeMin,dtimeMax,retVal);
  return retVal;

 } 



 Int_t RooTimePdfBkg::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,  const char* rangeName) const
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   if(matchArgs(allVars,analVars,time)) return 1;
   return 0;

 } 

 Double_t RooTimePdfBkg::intProto(Double_t x, Double_t a, Double_t c) const {

   
//   Double_t ret = -exp((c*(c-4*a*b))/(4*a*a))*erf(-c/2/a + a*x + b)+
//                   exp(c*x)*erf(a*x+b)+exp(c*x);

//   Double_t ret = -exp((c*(c+4*a*a))/(4*a*a))*erf(c/2/a + -a*x + a)+
//                   exp(c*x)*erf(-a*x+a)+exp(c*x);

   Double_t ret;
   Double_t hg;

   //printf("a=%g c=%g x=%g\n",a,c,x);

   Double_t z = -TMath::Exp(2*a*(x-1));

   //printf("z=%g 1/(1-z)=%g\n",z,1/(1-z));

   Double_t cd2da = c/2/a;

   if(z>-0.5) {
     hg = ROOT::Math::hyperg(1, cd2da, cd2da+1, z);
   } else {
     Double_t gb = ROOT::Math::tgamma(cd2da);
     Double_t gc = cd2da*gb; // Gamma(cd2da+1)
     Double_t gbma = gb/(cd2da-1); // Gamma(cd2da-1)
     Double_t gcma = gb;
     Double_t gamb = TMath::Pi()/sin(TMath::Pi()*cd2da)/gb; // Gamma(1-cd2da)

     hg = 1/(1-z)*gc*gbma/gb/gcma*
          ROOT::Math::hyperg(1, 1, 2-cd2da, 1/(1-z))+
          TMath::Power(1-z,-cd2da)*gc*gamb*
          ROOT::Math::hyperg(cd2da, cd2da, cd2da, 1/(1-z));
   }

   ret = 2*exp(c*x)*hg;

   //printf("hyperg=%g ret=%g\n",hg, ret);

   //printf("INSIDE INTPROTO %g %g %g %g %g\n",x,a,b,c,ret);
   return ret;
 }


 Double_t RooTimePdfBkg::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

  Double_t K1T = (exp(alpha1T*time.max())-exp(alpha1T*time.min()));
  Double_t K2T = (exp(alpha2T*time.max())-exp(alpha2T*time.min()));
  Double_t K1U = (exp(alpha1U*time.max())-exp(alpha1U*time.min()));
  Double_t K2U = (exp(alpha2U*time.max())-exp(alpha2U*time.min()));

  Double_t intT1Max = intProto(time.max(),c1T,alpha1T)/K1T;
  Double_t intT2Max = intProto(time.max(),c1T,alpha2T)/K2T;
  Double_t intT1Min = intProto(time.min(),c1T,alpha1T)/K1T;
  Double_t intT2Min = intProto(time.min(),c1T,alpha2T)/K2T;
  Double_t intU1Max = intProto(time.max(),c1U,alpha1U)/K1U;
  Double_t intU2Max = intProto(time.max(),c1U,alpha2U)/K2U;
  Double_t intU1Min = intProto(time.min(),c1U,alpha1U)/K1U;
  Double_t intU2Min = intProto(time.min(),c1U,alpha2U)/K2U;

  Double_t retValT = fracT*(intT1Max-intT1Min)+(1-fracT)*(intT2Max-intT2Min);
  Double_t retValU = fracU*(intU1Max-intU1Min)+(1-fracU)*(intU2Max-intU2Min);

  Double_t retVal = (q==0) ? retValU : retValT;
  Int_t iq = q;
  if(code==1) {
    //printf("INTEGRATION CODE 1 %d %g %g %g %g\n",iq,intT1Max,intT2Max,intT1Min,intT2Min);
    return retVal;

  }
  //printf("INTEGRATION CODE NOT 1 %g\n",retVal);
  return 0;


 } 

#endif

