/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOFSINCPFUNC_h
#define ROOFSINCPFUNC_h

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooFsinCPFunc : public RooAbsReal {
public:

  typedef enum { Bd, Bs } Mesons;

  RooFsinCPFunc() {} ; 
  RooFsinCPFunc(const char *name, const char *title,
                        RooAbsReal& _S,
                        RooAbsReal& _AP,
                        RooAbsReal& _OmegaOS, RooAbsReal& _OmegaSSpi,
                        RooAbsReal& _OmegabarOS, RooAbsReal& _OmegabarSSpi,
                        RooAbsCategory& _p, Mesons _meson);
  RooFsinCPFunc(const RooFsinCPFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooFsinCPFunc(*this,newname); }
  inline virtual ~RooFsinCPFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy S;
  RooRealProxy AP;
  RooRealProxy OmegaOS;
  RooRealProxy OmegaSSpi;
  RooRealProxy OmegabarOS; 
  RooRealProxy OmegabarSSpi;
  RooCategoryProxy p;
  
  Mesons meson;

  Double_t evaluate() const ;
  
private:

  ClassDef(RooFsinCPFunc,1) // Your description goes here...
};
 
#endif
