/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOFCOSFSTOCPFUNC_h
#define ROOFCOSFSTOCPFUNC_h

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooFcosFStoCPFunc : public RooAbsReal {
public:

  typedef enum { Bd, Bs } Mesons;

  RooFcosFStoCPFunc() {} ; 
  RooFcosFStoCPFunc(const char *name, const char *title,
                        RooAbsReal& _ACP,
                        RooAbsReal& _Af,
                        RooAbsReal& _AP,
                        RooAbsReal& _OmegaOS, RooAbsReal& _OmegaSSpi,
                        RooAbsReal& _OmegabarOS, RooAbsReal& _OmegabarSSpi,
                        RooAbsCategory& _p, Mesons _meson);
  RooFcosFStoCPFunc(const RooFcosFStoCPFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooFcosFStoCPFunc(*this,newname); }
  inline virtual ~RooFcosFStoCPFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy ACP;
  RooRealProxy Af;
  RooRealProxy AP;
  RooRealProxy OmegaOS;
  RooRealProxy OmegaSSpi;
  RooRealProxy OmegabarOS; 
  RooRealProxy OmegabarSSpi;
  RooCategoryProxy p;
  
  Mesons meson;

  Double_t evaluate() const ;
  
private:

  ClassDef(RooFcosFStoCPFunc,1) // Your description goes here...
};
 
#endif
