/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOFCOSCPTOFSFUNC_h
#define ROOFCOSCPTOFSFUNC_h

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooFcosCPtoFSFunc : public RooAbsReal {
public:

  typedef enum { Bd, Bs } Mesons;

  RooFcosCPtoFSFunc() {} ; 
  RooFcosCPtoFSFunc(const char *name, const char *title,
                        RooAbsReal& _C,
                        RooAbsReal& _AP,
                        RooAbsReal& _epsKPI, RooAbsReal& _epsPIK,
                        RooAbsReal& _OmegaOS, RooAbsReal& _OmegaSSpi,
                        RooAbsReal& _OmegabarOS, RooAbsReal& _OmegabarSSpi,
                        RooAbsCategory& _p, Mesons _meson);
  RooFcosCPtoFSFunc(const RooFcosCPtoFSFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooFcosCPtoFSFunc(*this,newname); }
  inline virtual ~RooFcosCPtoFSFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy C;
  RooRealProxy AP;
  RooRealProxy epsKPI;
  RooRealProxy epsPIK;
  RooRealProxy OmegaOS;
  RooRealProxy OmegaSSpi;
  RooRealProxy OmegabarOS; 
  RooRealProxy OmegabarSSpi;
  RooCategoryProxy p;
  
  Mesons meson;

  Double_t evaluate() const ;
  
private:

  ClassDef(RooFcosCPtoFSFunc,1) // Your description goes here...
};
 
#endif
