/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOFSINHFUNC_h
#define ROOFSINHFUNC_h

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdfLocal.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooFsinhFunc : public RooAbsReal {
public:
  RooFsinhFunc() {} ; 
  RooFsinhFunc(const char *name, const char *title,
                        RooAbsReal& _ACP,
                        RooAbsReal& _Af,
                        RooAbsReal& _AP,
                        RooAbsReal& _eta,
                        RooAbsReal& _eps,
                        RooAbsReal& _p0,
                        RooAbsReal& _p1,
                        RooAbsReal& _epsbar,
                        RooAbsReal& _p0bar,
                        RooAbsReal& _p1bar,
                        RooAbsCategory& _p,
                        RooAbsCategory& _q,
                        RooHistPdfLocal& _etaHistPdf,
                        //TH1D& _etaHistPdf,
                        Double_t _etaHat);
  RooFsinhFunc(const RooFsinhFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooFsinhFunc(*this,newname); }
  inline virtual ~RooFsinhFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy ACP ;
  RooRealProxy Af ;
  RooRealProxy AP ;
  RooRealProxy eta ;
  RooRealProxy eps ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy epsbar ;
  RooRealProxy p0bar ;
  RooRealProxy p1bar ;
  RooCategoryProxy p ;
  RooCategoryProxy q ;
  RooRealProxy etaHistPdf ;
  //TH1D etaHistPdf ;

  Double_t etaHat;

  Double_t evaluate() const ;

private:

  ClassDef(RooFsinhFunc,1) // Your description goes here...
};
 
#endif
