/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOFCOSHFSTOCPFUNC_h
#define ROOFCOSHFSTOCPFUNC_h

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
#include "RooListProxy.h"
 
class RooFcoshFStoCPFunc : public RooAbsReal {
public:

  typedef enum { Bd, Bs } Mesons;

  RooFcoshFStoCPFunc() {} ; 
  RooFcoshFStoCPFunc(const char *name, const char *title,
                        RooAbsReal& _ACP, RooAbsReal& _Af,
                        RooAbsReal& _AP,
                        RooAbsReal& _OmegaOS, RooAbsReal& _OmegaSSpi,
                        RooAbsReal& _OmegabarOS, RooAbsReal& _OmegabarSSpi,
                        RooAbsCategory& _p, Mesons _meson);
  RooFcoshFStoCPFunc(const RooFcoshFStoCPFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooFcoshFStoCPFunc(*this,newname); }
  inline virtual ~RooFcoshFStoCPFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy ACP;
  RooRealProxy Af;
  RooRealProxy AP;
  RooRealProxy OmegaOS;
  RooRealProxy OmegaSSpi;
  RooRealProxy OmegabarOS; 
  RooRealProxy OmegabarSSpi;
  RooCategoryProxy p;
  
  Mesons meson;

  Double_t evaluate() const ;
  
private:

  ClassDef(RooFcoshFStoCPFunc,1) // Your description goes here...
};
 
#endif
