/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 
#ifndef ROOFCOSFSTOCPFUNC_cxx
#define ROOFCOSFSTOCPFUNC_cxx

// Your description goes here... 

#include "Riostream.h" 

#include "RooFcosFStoCPFunc.h" 
#include "RooAbsReal.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"

ClassImp(RooFcosFStoCPFunc) 

 RooFcosFStoCPFunc::RooFcosFStoCPFunc(const char *name, const char *title,
                        RooAbsReal& _ACP,
                        RooAbsReal& _Af,
                        RooAbsReal& _AP,
                        RooAbsReal& _OmegaOS, RooAbsReal& _OmegaSSpi,
                        RooAbsReal& _OmegabarOS, RooAbsReal& _OmegabarSSpi,
                        RooAbsCategory& _p, Mesons _meson) :
   RooAbsReal(name,title),
   ACP("ACP","ACP",this,_ACP),
   Af("Af","Af",this,_Af),
   AP("AP","AP",this,_AP),
   OmegaOS("OmegaOS","OmegaOS",this,_OmegaOS),
   OmegaSSpi("OmegaSSpi","OmegaSSpi",this,_OmegaSSpi),
   OmegabarOS("OmegabarOS","OmegabarOS",this,_OmegabarOS),
   OmegabarSSpi("OmegabarSSpi","OmegabarSSpi",this,_OmegabarSSpi),
   p("p","p",this,_p),
   meson(_meson)
 {
 } 


 RooFcosFStoCPFunc::RooFcosFStoCPFunc(const RooFcosFStoCPFunc& other, const char* name) :  
   RooAbsReal(other,name),
   ACP("ACP",this,other.ACP),
   Af("Af",this,other.Af),
   AP("AP",this,other.AP),
   OmegaOS("OmegaOS",this,other.OmegaOS),
   OmegaSSpi("OmegaSSpi",this,other.OmegaSSpi),
   OmegabarOS("OmegabarOS",this,other.OmegabarOS),
   OmegabarSSpi("OmegabarSSpi",this,other.OmegabarSSpi),
   p("p",this,other.p),
   meson(other.meson)

 { 
 } 



 Double_t RooFcosFStoCPFunc::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   Int_t ss = meson == Bd ? 0 : 2;
   return -(p==ss)*(ACP+Af)*((1-AP)*OmegaOS*OmegaSSpi-
                             (1+AP)*OmegabarOS*OmegabarSSpi);
 
 } 



 Int_t RooFcosFStoCPFunc::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   RooArgSet OmegaOSVars = RooArgSet();
   RooArgSet OmegaSSpiVars = RooArgSet();
   RooArgSet PVars = RooArgSet();

   Int_t codeOS   = OmegaOS.arg().isConstant() ? 0 :
                    OmegaOS.arg().getAnalyticalIntegral(allVars, OmegaOSVars, rangeName);
   Int_t codeSSpi = OmegaSSpi.arg().isConstant() ? 0 :
                    OmegaSSpi.arg().getAnalyticalIntegral(allVars, OmegaSSpiVars, rangeName);
   Int_t codeP = 0;
   if (matchArgs(allVars,PVars,p)) codeP = 1;

   analVars.add(OmegaOSVars); 
   analVars.add(OmegaSSpiVars); 
   analVars.add(PVars);

   Int_t retCode = (codeP << 6) +
                   (codeSSpi << 3) +
                   (codeOS);

   return retCode;

 } 



 Double_t RooFcosFStoCPFunc::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   Int_t ss = meson == Bd ? 0 : 2;
   if (code!=0) {
     Int_t codeP    = ( code & (7 << 6) ) >> 6;
     Int_t codeSSpi = ( code & (7 << 3) ) >> 3;
     Int_t codeOS   = ( code & 7);

     Double_t pInt            = codeP > 0    ? -(ACP+Af) : 
                                               -(p==ss)*(ACP+Af);
     Double_t OmegaSSpiInt    = codeSSpi > 0 ? OmegaSSpi.arg().analyticalIntegral(codeSSpi,rangeName) :
                                               OmegaSSpi;
     Double_t OmegabarSSpiInt = codeSSpi > 0 ? OmegabarSSpi.arg().analyticalIntegral(codeSSpi,rangeName) :
                                               OmegabarSSpi;
     Double_t OmegaOSInt      = codeOS > 0   ? OmegaOS.arg().analyticalIntegral(codeOS,rangeName) :
                                               OmegaOS;
     Double_t OmegabarOSInt   = codeOS > 0   ? OmegabarOS.arg().analyticalIntegral(codeOS,rangeName) :
                                               OmegabarOS;

     Double_t retVal = pInt*((1-AP)*OmegaOSInt*OmegaSSpiInt-
                             (1+AP)*OmegabarOSInt*OmegabarSSpiInt);
     return retVal;
   }

   return 0 ; 

 } 



#endif