/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 
#ifndef ROOFSINHFUNC_cxx
#define ROOFSINHFUNC_cxx

// Your description goes here... 

#include "Riostream.h" 

#include "RooFsinhFunc.h" 
#include "RooAbsReal.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdfLocal.h"
#include "RooDataHist.h"

ClassImp(RooFsinhFunc) 

 RooFsinhFunc::RooFsinhFunc(const char *name, const char *title, 
                        RooAbsReal& _ACP,
                        RooAbsReal& _Af,
                        RooAbsReal& _AP,
                        RooAbsReal& _eta,
                        RooAbsReal& _eps,
                        RooAbsReal& _p0,
                        RooAbsReal& _p1,
                        RooAbsReal& _epsbar,
                        RooAbsReal& _p0bar,
                        RooAbsReal& _p1bar,
                        RooAbsCategory& _p,
                        RooAbsCategory& _q,
                        RooHistPdfLocal& _etaHistPdf,
                        //TH1D& _etaHistPdf,
                        Double_t _etaHat) :
   RooAbsReal(name,title), 
   ACP("ACP","ACP",this,_ACP),
   Af("Af","Af",this,_Af),
   AP("AP","AP",this,_AP),
   eta("eta","eta",this,_eta),
   eps("eps","eps",this,_eps),
   p0("p0","p0",this,_p0),
   p1("p1","p1",this,_p1),
   epsbar("epsbar","epsbar",this,_epsbar),
   p0bar("p0bar","p0bar",this,_p0bar),
   p1bar("p1bar","p1bar",this,_p1bar),
   p("p","p",this,_p),
   q("q","q",this,_q),
   etaHistPdf("etaHistPdf","etaHistPdf",this,_etaHistPdf),
   //etaHistPdf(_etaHistPdf),
   etaHat(_etaHat)
 {
 } 


 RooFsinhFunc::RooFsinhFunc(const RooFsinhFunc& other, const char* name) :  
   RooAbsReal(other,name), 
   ACP("ACP",this,other.ACP),
   Af("Af",this,other.Af),
   AP("AP",this,other.AP),
   eta("eta",this,other.eta),
   eps("eps",this,other.eps),
   p0("p0",this,other.p0),
   p1("p1",this,other.p1),
   epsbar("epsbar",this,other.epsbar),
   p0bar("p0bar",this,other.p0bar),
   p1bar("p1bar",this,other.p1bar),
   p("p",this,other.p),
   q("q",this,other.q),
   etaHistPdf("etaHistPdf",this,other.etaHistPdf),
   //etaHistPdf(other.etaHistPdf),
   etaHat(other.etaHat)
 { 
 } 



 Double_t RooFsinhFunc::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 0.; 
 } 



 Int_t RooFsinhFunc::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   printf("STICAZZI SINH "); //analVars.Print();
   Int_t code = 0;
   if (matchArgs(allVars,analVars,eta,p,q)) { analVars.Print(); return 7 ;} 
   if (matchArgs(allVars,analVars,q,p)) { analVars.Print(); return 6 ; }
   if (matchArgs(allVars,analVars,eta,p)) { analVars.Print(); return 5 ;} 
   if (matchArgs(allVars,analVars,eta,q)) { analVars.Print(); return 4 ;} 
   if (matchArgs(allVars,analVars,p)) { analVars.Print(); return 3 ; }
   if (matchArgs(allVars,analVars,q)) { analVars.Print(); return 2 ; }
   if (matchArgs(allVars,analVars,eta)) { analVars.Print(); return 1 ; }
   return 0 ; 
 } 



 Double_t RooFsinhFunc::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x


   if (code==1) return 1.; // Integral in eta 
   if (code==2) return 1.; // Integral in q
   if (code==3) return 1.; // Integral in p
   if (code==4) return 1.; // Integral in eta,q
   if (code==5) return 1.; // Integral in eta,p
   if (code==6) return 1.; // Integral in q,p
   if (code==7) return 1.; // Integral in eta,q,p
   return 0 ; 
 } 



#endif