/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOFSINHCPFUNC_h
#define ROOFSINHCPFUNC_h

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
#include "RooListProxy.h"
 
class RooFsinhCPFunc : public RooAbsReal {
public:

  typedef enum { Bd, Bs } Mesons;

  RooFsinhCPFunc() {} ; 
  RooFsinhCPFunc(const char *name, const char *title,
                        RooAbsReal& _C, RooAbsReal& _S, RooAbsReal& _D,
                        RooAbsReal& _AP,
                        RooAbsReal& _OmegaOS, RooAbsReal& _OmegaSSpi,
                        RooAbsReal& _OmegabarOS, RooAbsReal& _OmegabarSSpi,
                        RooAbsCategory& _p, Mesons _meson);
  RooFsinhCPFunc(const RooFsinhCPFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooFsinhCPFunc(*this,newname); }
  inline virtual ~RooFsinhCPFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy C;
  RooRealProxy S;
  RooRealProxy D;
  RooRealProxy AP;
  RooRealProxy OmegaOS;
  RooRealProxy OmegaSSpi;
  RooRealProxy OmegabarOS; 
  RooRealProxy OmegabarSSpi;
  RooCategoryProxy p;
  
  Mesons meson;

  Double_t evaluate() const ;
  
private:

  ClassDef(RooFsinhCPFunc,1) // Your description goes here...
};
 
#endif
