/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOFCOSFUNC_h
#define ROOFCOSFUNC_h

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooFcosFunc : public RooAbsReal {
public:

  RooFcosFunc() {} ; 
  RooFcosFunc(const char *name, const char *title,
                        RooAbsReal& _ACP,
                        RooAbsReal& _Af,
                        RooAbsReal& _AP,
                        RooAbsReal& _OmegaOS, RooAbsReal& _OmegaSSpi, RooAbsReal& _OmegaSSk,
                        RooAbsReal& _OmegabarOS, RooAbsReal& _OmegabarSSpi, RooAbsReal& _OmegabarSSk,
                        RooAbsCategory& _p);
  RooFcosFunc(const RooFcosFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooFcosFunc(*this,newname); }
  inline virtual ~RooFcosFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy ACP;
  RooRealProxy Af;
  RooRealProxy AP;
  RooRealProxy OmegaOS;
  RooRealProxy OmegaSSpi;
  RooRealProxy OmegaSSk;
  RooRealProxy OmegabarOS; 
  RooRealProxy OmegabarSSpi;
  RooRealProxy OmegabarSSk;
  RooCategoryProxy p;
  
  Double_t evaluate() const ;
  
private:

  ClassDef(RooFcosFunc,1) // Your description goes here...
};
 
#endif
