/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOFCOSCPFUNC_h
#define ROOFCOSCPFUNC_h

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooFcosCPFunc : public RooAbsReal {
public:

  typedef enum { Bd, Bs } Mesons;

  RooFcosCPFunc() {} ; 
  RooFcosCPFunc(const char *name, const char *title,
                        RooAbsReal& _C,
                        RooAbsReal& _AP,
                        RooAbsReal& _OmegaOS, RooAbsReal& _OmegaSSpi,
                        RooAbsReal& _OmegabarOS, RooAbsReal& _OmegabarSSpi,
                        RooAbsCategory& _p, Mesons _meson);
  RooFcosCPFunc(const RooFcosCPFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooFcosCPFunc(*this,newname); }
  inline virtual ~RooFcosCPFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy C;
  RooRealProxy AP;
  RooRealProxy OmegaOS;
  RooRealProxy OmegaSSpi;
  RooRealProxy OmegabarOS; 
  RooRealProxy OmegabarSSpi;
  RooCategoryProxy p;
  
  Mesons meson;

  Double_t evaluate() const ;
  
private:

  ClassDef(RooFcosCPFunc,1) // Your description goes here...
};
 
#endif
