/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOJOHNSONFUNC
#define ROOJOHNSONFUNC

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooJohnsonFunc : public RooAbsPdf {
public:
  RooJohnsonFunc() {} ; 
  RooJohnsonFunc(const char *name, const char *title,
	      RooAbsReal& _mass,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma1,
	      RooAbsReal& _alpha1,
	      RooAbsReal& _alpha2);
  RooJohnsonFunc(const RooJohnsonFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooJohnsonFunc(*this,newname); }
  inline virtual ~RooJohnsonFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy mass ;
  RooRealProxy mean ;
  RooRealProxy sigma1 ;
  RooRealProxy alpha1 ;
  RooRealProxy alpha2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooJohnsonFunc,1) // Your description goes here...
};
 
#endif
