/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOOMEGABKGFUNC
#define ROOOMEGABKGFUNC

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooOmegaBkgFunc : public RooAbsPdf {
public:

  /// flags
  
  RooOmegaBkgFunc() {} ; 
  RooOmegaBkgFunc(const char *name, const char *title,
               RooAbsCategory& _q,
               RooAbsReal& _eta,
               RooAbsReal& _eps,
               RooAbsReal& _epsAsym,
               RooHistPdf& _etaHistPdf);
  RooOmegaBkgFunc(const RooOmegaBkgFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooOmegaBkgFunc(*this,newname); }
  inline virtual ~RooOmegaBkgFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooCategoryProxy q ;
  RooRealProxy eta ;
  RooRealProxy eps ;
  RooRealProxy epsAsym ;
  RooRealProxy etaHistPdf ;
 
  Double_t evaluate() const ;
  
private:

  ClassDef(RooOmegaBkgFunc,1) // Your description goes here...
};
 
#endif
