/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOOMEGABKGFUNCNEW
#define ROOOMEGABKGFUNCNEW

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooOmegaBkgFuncNew : public RooAbsPdf {
public:

  /// flags
  
  RooOmegaBkgFuncNew() {} ; 
  RooOmegaBkgFuncNew(const char *name, const char *title,
                            RooAbsCategory& _qi,
                            RooAbsCategory& _qj,
                            RooAbsReal& _etai,
                            RooAbsReal& _etaj,
                            RooAbsReal& _epsi0,
                            RooAbsReal& _epsi1,
                            RooAbsReal& _epsAsymi0,
                            RooAbsReal& _epsAsymi1,
                            RooAbsReal& _epsj,
                            RooAbsReal& _epsAsymj,
                            RooHistPdf& _etaHistPdfi,
                            RooHistPdf& _etaHistPdfj);
  RooOmegaBkgFuncNew(const RooOmegaBkgFuncNew& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooOmegaBkgFuncNew(*this,newname); }
  inline virtual ~RooOmegaBkgFuncNew() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooCategoryProxy qi;
  RooCategoryProxy qj;
  RooRealProxy etai;
  RooRealProxy etaj;
  RooRealProxy epsi0;
  RooRealProxy epsi1;
  RooRealProxy epsAsymi0;
  RooRealProxy epsAsymi1;
  RooRealProxy epsj;
  RooRealProxy epsAsymj;
  RooRealProxy etaHistPdfi;
  RooRealProxy etaHistPdfj;
  Double_t evaluate() const ;
  
private:

  ClassDef(RooOmegaBkgFuncNew,1) // Your description goes here...
};
 
#endif
