/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h"

#include "RooOmegaBkgFuncCat.h"
#include "RooAbsPdf.h"
#include <math.h>
#include "TMath.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooRealVar.h"
#include "RooArgList.h"

ClassImp(RooOmegaBkgFuncCat) 

 RooOmegaBkgFuncCat::RooOmegaBkgFuncCat(const char *name, const char *title,
                            RooAbsCategory& _q,
                            RooArgList& _epsList,
                            RooArgList& _epsAsymList) :
   RooAbsPdf(name,title),
   q("q","q",this,_q),
   epsList("epsList","epsList",this),
   epsAsymList("epsAsymList","epsAsymList",this)
 {

   for(Int_t i = 0; i < _epsList.getSize(); i++) {

     epsList.add(_epsList[i]);
     epsAsymList.add(_epsAsymList[i]);

   }

 } 


 RooOmegaBkgFuncCat::RooOmegaBkgFuncCat(const RooOmegaBkgFuncCat& other, const char* name) :  
   RooAbsPdf(other,name),
   q("q",this,other.q),
   epsList("epsList",this,other.epsList),
   epsAsymList("epsAsymList",this,other.epsAsymList)
 { 
 } 



 Double_t RooOmegaBkgFuncCat::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

   Double_t retVal = 0;
   Double_t eps = 0, epsAsym = 0, untag = 0;
   Double_t epsB = 0, epsBbar = 0;
   for(Int_t iCat = 0; iCat < epsList.getSize(); iCat++) {

     eps = ((RooAbsReal&) epsList[iCat]).getVal();
     epsAsym = ((RooAbsReal&) epsAsymList[iCat]).getVal();

     epsB     = 0.5*eps*(1+epsAsym);
     epsBbar  = 0.5*eps*(1-epsAsym);

     retVal += (q==(iCat+1))*epsB+
               (q==-(iCat+1))*epsBbar;
     untag  += (epsB+epsBbar);

   }
   
   retVal += (q==0)*(1-untag);
   return retVal;
 
 } 



 Int_t RooOmegaBkgFuncCat::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   if (matchArgs(allVars,analVars,q))     return 1 ; 
   return 0 ; 
 } 



 Double_t RooOmegaBkgFuncCat::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   if (code==1) return 1;
   return 0 ; 

 } 



