/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooOmegaBkgFunc.h" 
#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"

ClassImp(RooOmegaBkgFunc) 

 RooOmegaBkgFunc::RooOmegaBkgFunc(const char *name, const char *title,
                            RooAbsCategory& _q,
                            RooAbsReal& _eta,
                            RooAbsReal& _eps,
                            RooAbsReal& _epsAsym,
                            RooHistPdf& _etaHistPdf) :
   RooAbsPdf(name,title),
   q("q","q",this,_q),
   eta("eta","eta",this,_eta),
   eps("eps","eps",this,_eps),
   epsAsym("epsAsym","epsAsym",this,_epsAsym),
   etaHistPdf("etaHistPdf","etaHistPdf",this,_etaHistPdf)
 {
 } 


 RooOmegaBkgFunc::RooOmegaBkgFunc(const RooOmegaBkgFunc& other, const char* name) :  
   RooAbsPdf(other,name),
   q("q",this,other.q),
   eta("eta",this,other.eta),
   eps("eps",this,other.eps),
   epsAsym("epsAsym",this,other.epsAsym),
   etaHistPdf("etaHistPdf",this,other.etaHistPdf)
 { 
 } 



 Double_t RooOmegaBkgFunc::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   Double_t rangeEta = eta.max()-eta.min();

   Double_t epsB     = 0.5*eps*(1+epsAsym);
   Double_t epsBbar  = 0.5*eps*(1-epsAsym);
   
   Double_t retVal   = (q==1)*epsB*etaHistPdf+
                       (q==-1)*epsBbar*etaHistPdf+
                       (q==0)*(1-epsB-epsBbar)/rangeEta;

   return retVal;
 
 } 



 Int_t RooOmegaBkgFunc::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   Int_t code = 0;
   if (matchArgs(allVars,analVars,eta,q)) return 3 ; 
   if (matchArgs(allVars,analVars,eta))   return 2 ; 
   if (matchArgs(allVars,analVars,q))     return 1 ; 
   return 0 ; 
 } 



 Double_t RooOmegaBkgFunc::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   if (code==3)  {

     Double_t epsB     = 0.5*eps*(1+epsAsym);
     Double_t epsBbar  = 0.5*eps*(1-epsAsym);

     return 1;//epsB+epsBbar;
   }

   if (code==2) { // Integral in eta 

     Double_t epsB     = 0.5*eps*(1+epsAsym); 
     Double_t epsBbar  = 0.5*eps*(1-epsAsym); 

     Double_t retVal   = (q==1)*epsB+
                         (q==-1)*epsBbar+
                         (q==0)*(1-epsB-epsBbar);

     return retVal;
   }
   if (code==1) { // Integral in q
     Double_t rangeEta = eta.max()-eta.min();

     Double_t retVal = eps*etaHistPdf+(1-eps)/rangeEta;
     
     return retVal;
   } 

   return 0 ; 

 } 



