/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOOMEGAFUNCCAT
#define ROOOMEGAFUNCCAT

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooListProxy.h"

class RooRealVar;
class RooArgList ;
 
class RooOmegaFuncCat : public RooAbsReal {
public:

  /// flags
  typedef enum { B, Bbar } Flags;
  
  RooOmegaFuncCat() {} ; 
  RooOmegaFuncCat(const char *name, const char *title,
               RooAbsCategory& _q,
               RooArgList& _epsList,
               RooArgList& _epsAsymList,
               RooArgList& _wList,
               RooArgList& _wAsymList,
               Flags _flag);
  RooOmegaFuncCat(const RooOmegaFuncCat& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooOmegaFuncCat(*this,newname); }
  inline virtual ~RooOmegaFuncCat() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooCategoryProxy q ;
  RooListProxy epsList ;
  RooListProxy epsAsymList ;
  RooListProxy wList ;
  RooListProxy wAsymList ;

  Flags flag;
  
  Double_t evaluate() const ;
  
private:

  ClassDef(RooOmegaFuncCat,1) // Your description goes here...
};
 
#endif
