/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooOmegaBkgFuncNew.h" 
#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"

ClassImp(RooOmegaBkgFuncNew) 

 RooOmegaBkgFuncNew::RooOmegaBkgFuncNew(const char *name, const char *title,
                            RooAbsCategory& _qi,
                            RooAbsCategory& _qj,
                            RooAbsReal& _etai,
                            RooAbsReal& _etaj,
                            RooAbsReal& _epsi0,
                            RooAbsReal& _epsi1,
                            RooAbsReal& _epsAsymi0,
                            RooAbsReal& _epsAsymi1,
                            RooAbsReal& _epsj,
                            RooAbsReal& _epsAsymj,
                            RooHistPdf& _etaHistPdfi,
                            RooHistPdf& _etaHistPdfj) :
   RooAbsPdf(name,title),
   qi("qi","qi",this,_qi),
   qj("qj","qj",this,_qj),
   etai("etai","etai",this,_etai),
   etaj("etaj","etaj",this,_etaj),
   epsi0("epsi0","epsi0",this,_epsi0),
   epsi1("epsi1","epsi1",this,_epsi1),
   epsAsymi0("epsAsymi0","epsAsymi0",this,_epsAsymi0),
   epsAsymi1("epsAsymi1","epsAsymi1",this,_epsAsymi1),
   epsj("epsj","epsj",this,_epsj),
   epsAsymj("epsAsymj","epsAsymj",this,_epsAsymj),
   etaHistPdfi("etaHistPdfi","etaHistPdfi",this,_etaHistPdfi),
   etaHistPdfj("etaHistPdfj","etaHistPdfj",this,_etaHistPdfj)
 {
 } 


 RooOmegaBkgFuncNew::RooOmegaBkgFuncNew(const RooOmegaBkgFuncNew& other, const char* name) :  
   RooAbsPdf(other,name),
   qi("qi",this,other.qi),
   qj("qj",this,other.qj),
   etai("etai",this,other.etai),
   etaj("etaj",this,other.etaj),
   epsi0("epsi0",this,other.epsi0),
   epsi1("epsi1",this,other.epsi1),
   epsAsymi0("epsAsymi0",this,other.epsAsymi0),
   epsAsymi1("epsAsymi1",this,other.epsAsymi1),
   epsj("epsj",this,other.epsj),
   epsAsymj("epsAsymj",this,other.epsAsymj),
   etaHistPdfi("etaHistPdfi",this,other.etaHistPdfi),
   etaHistPdfj("etaHistPdfj",this,other.etaHistPdfj)
 { 
 } 



 Double_t RooOmegaBkgFuncNew::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   Double_t rangeEtai = etai.max()-etai.min();
   Double_t rangeEtaj = etaj.max()-etaj.min();

   Double_t epsi0B     = 0.5*epsi0*(1+epsAsymi0);
   Double_t epsi0Bbar  = 0.5*epsi0*(1-epsAsymi0);
   Double_t epsi1B     = 0.5*epsi1*(1+epsAsymi1);
   Double_t epsi1Bbar  = 0.5*epsi1*(1-epsAsymi1);
   Double_t epsjB      = 0.5*epsj *(1+epsAsymj);
   Double_t epsjBbar   = 0.5*epsj *(1-epsAsymj);
   
   Double_t tagJ   = (qj==1) *epsjB*etaHistPdfj+
                     (qj==-1)*epsjBbar*etaHistPdfj;
   Double_t untagJ = (qj==0)*(1-epsjB-epsjBbar)/rangeEtaj;

   Double_t tagI   = (qi==1) *epsi1B*etaHistPdfi+
                     (qi==-1)*epsi1Bbar*etaHistPdfi+
                     (qi==0)*(1-epsi1B-epsi1Bbar)/rangeEtai;
   Double_t untagI = (qi==1) *epsi0B*etaHistPdfi+
                     (qi==-1)*epsi0Bbar*etaHistPdfi+
                     (qi==0)*(1-epsi0B-epsi0Bbar)/rangeEtai;

   Double_t retVal = tagJ*tagI+untagJ*untagI;

   return retVal;
 
 } 



 Int_t RooOmegaBkgFuncNew::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   Int_t code = 0;
   if (matchArgs(allVars,analVars,qi,qj,etai,etaj)) return 15 ; 
   if (matchArgs(allVars,analVars,qj,etai,etaj))    return 14 ; 
   if (matchArgs(allVars,analVars,qi,etai,etaj))    return 13 ; 
   if (matchArgs(allVars,analVars,qi,qj,etaj))      return 12 ; 
   if (matchArgs(allVars,analVars,qi,qj,etai))      return 11 ; 
   if (matchArgs(allVars,analVars,etai,etaj))       return 10 ; 
   if (matchArgs(allVars,analVars,qj,etaj))         return 9  ; 
   if (matchArgs(allVars,analVars,qj,etai))         return 8  ; 
   if (matchArgs(allVars,analVars,qi,etaj))         return 7  ; 
   if (matchArgs(allVars,analVars,qi,etai))         return 6  ; 
   if (matchArgs(allVars,analVars,qi,qj))           return 5  ; 
   if (matchArgs(allVars,analVars,etaj))            return 4  ; 
   if (matchArgs(allVars,analVars,etai))            return 3  ; 
   if (matchArgs(allVars,analVars,qj))              return 2  ; 
   if (matchArgs(allVars,analVars,qi))              return 1  ; 
   return 0 ; 
 } 



 Double_t RooOmegaBkgFuncNew::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   Double_t rangeEtai = etai.max()-etai.min();
   Double_t rangeEtaj = etaj.max()-etaj.min();

   Double_t epsi0B     = 0.5*epsi0*(1+epsAsymi0);
   Double_t epsi0Bbar  = 0.5*epsi0*(1-epsAsymi0);
   Double_t epsi1B     = 0.5*epsi1*(1+epsAsymi1);
   Double_t epsi1Bbar  = 0.5*epsi1*(1-epsAsymi1);
   Double_t epsjB      = 0.5*epsj *(1+epsAsymj);
   Double_t epsjBbar   = 0.5*epsj *(1-epsAsymj);
   
   Double_t tagJ   = (qj==1) *epsjB*etaHistPdfj+
                     (qj==-1)*epsjBbar*etaHistPdfj;
   Double_t untagJ = (qj==0)*(1-epsjB-epsjBbar)/rangeEtaj;

   Double_t tagI   = (qi==1) *epsi1B*etaHistPdfi+
                     (qi==-1)*epsi1Bbar*etaHistPdfi+
                     (qi==0)*(1-epsi1B-epsi1Bbar)/rangeEtai;
   Double_t untagI = (qi==1) *epsi0B*etaHistPdfi+
                     (qi==-1)*epsi0Bbar*etaHistPdfi+
                     (qi==0)*(1-epsi0B-epsi0Bbar)/rangeEtai;

   Double_t IntQiEtai0 = 1;
   Double_t IntQiEtai1 = 1;
   Double_t IntQi0 = epsi0*etaHistPdfi+(1-epsi0)/rangeEtai;
   Double_t IntQi1 = epsi1*etaHistPdfi+(1-epsi1)/rangeEtai;
   Double_t IntEtai0 = (qi==1) *epsi0B+
                       (qi==-1)*epsi0Bbar+
                       (qi==0) *(1-epsi0B-epsi0Bbar);
   Double_t IntEtai1 = (qi==1) *epsi1B+
                       (qi==-1)*epsi1Bbar+
                       (qi==0) *(1-epsi1B-epsi1Bbar);



   Double_t retVal = 0;
   if (code==15) { //qi,qj,etai,etaj 
    return 1;
   }
   else if(code==14) { //qj,etai,etaj
     retVal = epsj*IntEtai1+
             (1-epsj)*IntEtai0;
     return retVal;
   }
   else if(code==13) { //qi,etai,etaj
     retVal = (qj==1)*epsjB+
              (qj==-1)*epsjBbar+
              (qj==0)*(1-epsjB-epsjBbar);
     return retVal;
   }
   else if(code==12) { // qi,qj,etaj
     retVal = epsj*IntQi1+
              (1-epsj)*IntQi0;
     return retVal;
   }
   else if(code==11) { // qi,qj,etai
     retVal = epsj*etaHistPdfj+(1-epsj)/rangeEtaj;
     return retVal;
   }
   else if(code==10) { // etai,etaj
     retVal = (qj==1)*epsjB*IntEtai1+
              (qj==-1)*epsjBbar*IntEtai1+
              (qj==0)*(1-epsjB-epsjBbar)*IntEtai0;
     return retVal;
   }
   else if(code==9) { // qj,etaj
     retVal = epsj*tagI+
              (1-epsj)*untagI;
     return retVal;
   }
   else if(code==8) { // qj,etai
     retVal = epsj*etaHistPdfj*IntEtai1+
              (1-epsj)/rangeEtaj*IntEtai0;
     return retVal;
   }
   else if(code==7) { // qi,etaj
     retVal = (qj==1) *epsjB*IntQi1+
              (qj==-1)*epsjBbar*IntQi1+
              (qj==0) *(1-epsjB-epsjBbar)*IntQi0;
     return retVal;
   }
   else if(code==6) { // qi,etai 
     retVal = (qj==1) *etaHistPdfj+
              (qj==-1)*etaHistPdfj+
              (qj==0) *(1-epsjB-epsjBbar)/rangeEtaj;
     return retVal;
   }
   else if(code==5) { // qi,qj
     retVal = epsj*etaHistPdfj*IntQi1+
              (1-epsj)/rangeEtaj*IntQi0;
   }
   else if(code==4) { // etaj 
     retVal = (qj==1) *epsjB*tagI+
              (qj==-1)*epsjBbar*tagI+
              (qj==0) *(1-epsjB-epsjBbar)*untagI;
     return retVal;
   }
   else if(code==3) { // etai
     retVal = (qj==1) *epsjB*etaHistPdfj*IntEtai1+
              (qj==-1)*epsjBbar*etaHistPdfj*IntEtai1+
              (qj==0) *(1-epsjB-epsjBbar)/rangeEtaj*IntEtai0;
     return retVal;    
   }
   else if(code==2) { //qj  
     retVal = epsj*etaHistPdfj*tagI+
              (1-epsj)/rangeEtaj*untagI;
     return retVal;        
   }
   else if(code==1) { // qi
     retVal = (qj==1) *epsjB*etaHistPdfj*IntQi1+
              (qj==-1)*epsjBbar*etaHistPdfj*IntQi1+
              (qj==0) *(1-epsjB-epsjBbar)/rangeEtaj*IntQi0;
     return retVal;            
   }
   return 0 ; 

 } 



