/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooOmegaFuncCat.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooRealVar.h"
#include "RooArgList.h"

ClassImp(RooOmegaFuncCat) 

 RooOmegaFuncCat::RooOmegaFuncCat(const char *name, const char *title,
                            RooAbsCategory& _q,
                            RooArgList& _epsList,
                            RooArgList& _epsAsymList,
                            RooArgList& _wList,
                            RooArgList& _wAsymList,
                            Flags _flag) :
   RooAbsReal(name,title),
   q("q","q",this,_q),
   epsList("epsList","epsList",this),
   epsAsymList("epsAsymList","epsAsymList",this),
   wList("wList","wList",this),
   wAsymList("wAsymList","wAsymList",this),
   flag(_flag)
 {

   for(Int_t i = 0; i < _epsList.getSize(); i++) {

     epsList.add(_epsList[i]);
     epsAsymList.add(_epsAsymList[i]);
     wList.add(_wList[i]);
     wAsymList.add(_wAsymList[i]);

   }
 } 


 RooOmegaFuncCat::RooOmegaFuncCat(const RooOmegaFuncCat& other, const char* name) :  
   RooAbsReal(other,name),
   q("q",this,other.q),
   epsList("epsList",this,other.epsList),
   epsAsymList("epsAsymList",this,other.epsAsymList),
   wList("wList",this,other.wList),
   wAsymList("wAsymList",this,other.wAsymList),
   flag(other.flag)
 { 
 } 



 Double_t RooOmegaFuncCat::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   Int_t ss = flag == B ? 1 : -1;

   Int_t sticazzi = q;
   Double_t retVal = 0;
   Double_t eps = 0, epsAsym = 0, w = 0, wAsym = 0, untag = 0;
   Double_t epsB = 0, wB = 0;
   for(Int_t iCat = 0; iCat < epsList.getSize(); iCat++) {

     eps = ((RooAbsReal&) epsList[iCat]).getVal();
     epsAsym = ((RooAbsReal&) epsAsymList[iCat]).getVal();
     w   = ((RooAbsReal&) wList[iCat]).getVal();
     wAsym   = ((RooAbsReal&) wAsymList[iCat]).getVal();

     epsB = eps*(1+ss*epsAsym);
     wB = w*(1+ss*wAsym);

     retVal += (q==ss*(iCat+1))*epsB*(1-wB)+
               (q==-ss*(iCat+1))*epsB*wB;
     untag += epsB;

   }

   retVal += (q==0)*(1-untag);

   return retVal; 
 
 } 



 Int_t RooOmegaFuncCat::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   if (matchArgs(allVars,analVars,q))     return 1 ; 
   return 0 ; 
 } 



 Double_t RooOmegaFuncCat::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   if (code==1) return 1;

   return 0 ; 

 } 



