/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooOmegaFunc.h" 
#include "RooAbsReal.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"

ClassImp(RooOmegaFunc) 

 RooOmegaFunc::RooOmegaFunc(const char *name, const char *title,
                            RooAbsCategory& _q,
                            RooAbsReal& _eta,
                            RooAbsReal& _eps,
                            RooAbsReal& _p0,
                            RooAbsReal& _p1,
                            RooAbsReal& _epsAsym,
                            RooAbsReal& _deltap0,
                            RooAbsReal& _deltap1,
                            RooHistPdf& _etaHistPdf,
                            RooAbsReal& _etaHat,
                            Double_t    _etaAvg,
                            Flags _flag) :
   RooAbsReal(name,title),
   q("q","q",this,_q),
   eta("eta","eta",this,_eta),
   eps("eps","eps",this,_eps),
   p0("p0","p0",this,_p0),
   p1("p1","p1",this,_p1),
   epsAsym("epsAsym","epsAsym",this,_epsAsym),
   deltap0("deltap0","deltap0",this,_deltap0),
   deltap1("deltap1","deltap1",this,_deltap1),
   etaHistPdf("etaHistPdf","etaHistPdf",this,_etaHistPdf),
   etaHat("etaHat","etaHat",this,_etaHat),
   etaAvg(_etaAvg),
   flag(_flag)
 {
 } 


 RooOmegaFunc::RooOmegaFunc(const RooOmegaFunc& other, const char* name) :  
   RooAbsReal(other,name),
   q("q",this,other.q),
   eta("eta",this,other.eta),
   eps("eps",this,other.eps),
   p0("p0",this,other.p0),
   p1("p1",this,other.p1),
   epsAsym("epsAsym",this,other.epsAsym),
   deltap0("deltap0",this,other.deltap0),
   deltap1("deltap1",this,other.deltap1),
   etaHistPdf("etaHistPdf",this,other.etaHistPdf),
   etaHat("etaHat",this,other.etaHat),
   etaAvg(other.etaAvg),
   flag(other.flag)
 { 
 } 



 Double_t RooOmegaFunc::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   Double_t rangeEta = eta.max()-eta.min();
   Int_t ss = flag == B ? 1 : -1;

   
   Double_t epsB     = eps*(1+ss*epsAsym);
   Double_t p0B      = p0*(1+ss*deltap0);
   Double_t p1B      = p1*(1+ss*deltap1);
   Double_t retVal   = (q==ss)*epsB*(1-p0B-p1B*(eta-etaHat))*etaHistPdf+
                       (q==-ss)*epsB*(p0B+p1B*(eta-etaHat))*etaHistPdf+
                       (q==0)*(1-epsB)/rangeEta;

   return retVal;
 
 } 



 Int_t RooOmegaFunc::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   Int_t code = 0;

  
   if (matchArgs(allVars,analVars,eta,q)) code = 3;
   else if (matchArgs(allVars,analVars,eta))   code = 2;
   else if (matchArgs(allVars,analVars,q))     code = 1;
   //printf("CAZZI%d\n",code);
   //if(allVars.getSize()) allVars.Print("v");

   return code ; 
 } 



 Double_t RooOmegaFunc::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   if ( code == 3 ) {

     Int_t ss = flag == B ? 1 : -1;
     Double_t epsB     = eps*(1+ss*epsAsym);
     Double_t p0B      = p0*(1+ss*deltap0);
     Double_t p1B      = p1*(1+ss*deltap1);

     Double_t retVal   = epsB*(1-p0B-p1B*(etaAvg-etaHat))+
                         epsB*(p0B+p1B*(etaAvg-etaHat))+
                         (1-epsB);

     return retVal;

   }

   if ( code == 2 ) { // Integral in eta 
     Int_t ss = flag == B ? 1 : -1;

     Double_t epsB     = eps*(1+ss*epsAsym); 
     Double_t p0B      = p0*(1+ss*deltap0);  
     Double_t p1B      = p1*(1+ss*deltap1);  

     Double_t retVal   = (q==ss)*epsB*(1-p0B-p1B*(etaAvg-etaHat))+
                         (q==-ss)*epsB*(p0B+p1B*(etaAvg-etaHat))+
                         (q==0)*(1-epsB);

     return retVal;
   }

   if ( code == 1 ) { // Integral in q
     Double_t rangeEta = eta.max()-eta.min();
     Int_t ss = flag == B ? 1 : -1;

     Double_t epsB   = eps*(1+ss*epsAsym);
     Double_t retVal = epsB*etaHistPdf+(1-epsB)/rangeEta;
     
     return retVal;
   } 
   return 0 ; 

 } 



