/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOOMEGABKGFUNCCAT
#define ROOOMEGABKGFUNCCAT

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooListProxy.h"

class RooRealVar;
class RooArgList ;

class RooOmegaBkgFuncCat : public RooAbsPdf {
public:

  /// flags
  
  RooOmegaBkgFuncCat() {} ; 
  RooOmegaBkgFuncCat(const char *name, const char *title,
               RooAbsCategory& _q,
               RooArgList& _epsList,
               RooArgList& _epsAsymList);
  RooOmegaBkgFuncCat(const RooOmegaBkgFuncCat& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooOmegaBkgFuncCat(*this,newname); }
  inline virtual ~RooOmegaBkgFuncCat() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooCategoryProxy q ;
  RooListProxy epsList ;
  RooListProxy epsAsymList ;

  Double_t evaluate() const ;
  
private:

  ClassDef(RooOmegaBkgFuncCat,1) // Your description goes here...
};
 
#endif
