/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOOMEGAFUNCSS
#define ROOOMEGAFUNCSS

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooOmegaFuncSS : public RooAbsReal {
public:

  /// flags
  typedef enum { B, Bbar } Flags;
  typedef enum { Tag, Untag } FlagsTag;
  
  RooOmegaFuncSS() {} ; 
  RooOmegaFuncSS(const char *name, const char *title,
               RooAbsCategory& _q,
               RooAbsReal& _eta,
               RooAbsReal& _time,
               RooAbsReal& _eps,
               RooAbsReal& _p0,
               RooAbsReal& _p1,
               RooAbsReal& _epsAsym,
               RooAbsReal& _deltap0,
               RooAbsReal& _deltap1,
               RooHistPdf& _etaHistPdf,
               RooAbsReal& _etaHat,
               Double_t _etaAvg,
               Flags _flag,
               FlagsTag _flagT);
  RooOmegaFuncSS(const RooOmegaFuncSS& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooOmegaFuncSS(*this,newname); }
  inline virtual ~RooOmegaFuncSS() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
  //virtual Bool_t forceAnalyticalInt(const RooAbsArg& /*dep*/) const { 
  //  return kTRUE ; 
  //}

protected:

  RooCategoryProxy q ;
  RooRealProxy eta ;
  RooRealProxy time ;
  RooRealProxy eps ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy epsAsym ;
  RooRealProxy deltap0 ;
  RooRealProxy deltap1 ;
  RooRealProxy etaHistPdf ;
  RooRealProxy etaHat;

  Double_t etaAvg;
  Flags flag;
  FlagsTag flagT;
  
  Double_t evaluate() const ;
  //Double_t eps_t() const;

private:

  ClassDef(RooOmegaFuncSS,1) // Your description goes here...
};
 
#endif
