/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOOMEGAFUNC
#define ROOOMEGAFUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooOmegaFunc : public RooAbsReal {
public:

  /// flags
  typedef enum { B, Bbar } Flags;
  
  RooOmegaFunc() {} ; 
  RooOmegaFunc(const char *name, const char *title,
               RooAbsCategory& _q,
               RooAbsReal& _eta,
               RooAbsReal& _eps,
               RooAbsReal& _p0,
               RooAbsReal& _p1,
               RooAbsReal& _epsAsym,
               RooAbsReal& _deltap0,
               RooAbsReal& _deltap1,
               RooHistPdf& _etaHistPdf,
               RooAbsReal& _etaHat,
               Double_t _etaAvg,
               Flags _flag);
  RooOmegaFunc(const RooOmegaFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooOmegaFunc(*this,newname); }
  inline virtual ~RooOmegaFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
  //virtual Bool_t forceAnalyticalInt(const RooAbsArg& /*dep*/) const { 
  //  return kTRUE ; 
  //}

protected:

  RooCategoryProxy q ;
  RooRealProxy eta ;
  RooRealProxy eps ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy epsAsym ;
  RooRealProxy deltap0 ;
  RooRealProxy deltap1 ;
  RooRealProxy etaHistPdf ;
  RooRealProxy etaHat;

  Double_t etaAvg;
  Flags flag;
  
  Double_t evaluate() const ;
  
private:

  ClassDef(RooOmegaFunc,1) // Your description goes here...
};
 
#endif
