/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSFITOMEGAFUNC
#define ROOSFITOMEGAFUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooSfitOmegaFunc : public RooAbsReal {
public:

  /// flags
  typedef enum { B, Bbar } Flags;
  
  RooSfitOmegaFunc() {} ; 
  RooSfitOmegaFunc(const char *name, const char *title,
               RooAbsCategory& _q,
               RooAbsReal& _eta,
               RooAbsReal& _eps,
               RooAbsReal& _p0,
               RooAbsReal& _p1,
               RooAbsReal& _epsAsym,
               RooAbsReal& _deltap0,
               RooAbsReal& _deltap1,
               RooHistPdf& _etaHistPdf,
               RooAbsReal& _etaHat,
               Flags _flag);
  RooSfitOmegaFunc(const RooSfitOmegaFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSfitOmegaFunc(*this,newname); }
  inline virtual ~RooSfitOmegaFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooCategoryProxy q ;
  RooRealProxy eta ;
  RooRealProxy eps ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy epsAsym ;
  RooRealProxy deltap0 ;
  RooRealProxy deltap1 ;
  RooRealProxy etaHistPdf ;
  RooRealProxy etaHat;

  Flags flag;
  
  Double_t evaluate() const ;
  
private:

  ClassDef(RooSfitOmegaFunc,1) // Your description goes here...
};
 
#endif
