/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTAGFUNC
#define ROOTAGFUNC

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooTagFunc : public RooAbsPdf {
public:

  typedef enum { KPI, PIPI, KK } State;
 
  RooTagFunc() {} ; 
  RooTagFunc(const char *name, const char *title,
               RooAbsCategory& _p,
               RooAbsReal& _ACP, 
               State _state);
  RooTagFunc(const RooTagFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTagFunc(*this,newname); }
  inline virtual ~RooTagFunc() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooCategoryProxy p ;
  RooRealProxy ACP ;
  State state;
 
  Double_t evaluate() const ;
  
private:

  ClassDef(RooTagFunc,1) // Your description goes here...
};
 
#endif
