/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTimeAccPhysPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooTimeAccPhysPdf) 

 RooTimeAccPhysPdf::RooTimeAccPhysPdf(const char *name, const char *title, 
                        RooAbsReal& _time,
                        RooAbsReal& _c1,
                        RooAbsReal& _c2,
                        RooAbsReal& _c3):
   RooAbsPdf(name,title), 
   time("time","time",this,_time),
   c1("c1","c1",this,_c1),
   c2("c2","c2",this,_c2),
   c3("c3","c3",this,_c3)
 { 
 } 


 RooTimeAccPhysPdf::RooTimeAccPhysPdf(const RooTimeAccPhysPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   time("time",this,other.time),
   c1("c1",this,other.c1),
   c2("c2",this,other.c2),
   c3("c3",this,other.c3)
 { 
 } 



 Double_t RooTimeAccPhysPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   //return 0.5*(1-TMath::Erf((c1-time)/time/c2)) ; 
   return 0.5*(1-TMath::Erf(c1*pow(time,c2)+c3)) ;
   //return 0.5*(1-TMath::Erf(c1*pow(time,c2))) ;
   //return 0.5*(1+TMath::Erf(c1*time+c2+c3*time*time)) ;
   //return 0.5*(1-exp(c1*time+c2*time*time));
 } 



