/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTAGFUNCNEW
#define ROOTAGFUNCNEW

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "TH1D.h"
 
class RooTagFuncNew : public RooAbsPdf {
public:

  typedef enum { KPI, PIPI, KK } State;
 
  RooTagFuncNew() {} ; 
  RooTagFuncNew(const char *name, const char *title,
               RooAbsCategory& _p,
               RooAbsCategory& _qi,
               RooAbsCategory& _qj,
               RooAbsReal& _ACP, 
               RooAbsReal& _Atagi, 
               RooAbsReal& _Atagj, 
               State _state);
  RooTagFuncNew(const RooTagFuncNew& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTagFuncNew(*this,newname); }
  inline virtual ~RooTagFuncNew() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooCategoryProxy p ;
  RooCategoryProxy qi ;
  RooCategoryProxy qj ;
  RooRealProxy ACP ;
  RooRealProxy Atagi ;
  RooRealProxy Atagj ;
  State state;
 
  Double_t evaluate() const ;
  
private:

  ClassDef(RooTagFuncNew,1) // Your description goes here...
};
 
#endif
