/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTimeAccPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooTimeAccPdf) 

 RooTimeAccPdf::RooTimeAccPdf(const char *name, const char *title, 
                        RooAbsReal& _time,
                        RooAbsReal& _c1,
                        RooAbsReal& _c2):
   RooAbsPdf(name,title), 
   time("time","time",this,_time),
   c1("c1","c1",this,_c1),
   c2("c2","c2",this,_c2)
 { 
 } 


 RooTimeAccPdf::RooTimeAccPdf(const RooTimeAccPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   time("time",this,other.time),
   c1("c1",this,other.c1),
   c2("c2",this,other.c2)
 { 
 } 



 Double_t RooTimeAccPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   //return 0.5*(1-TMath::Erf((c1-time)/time/c2)) ; 
   return 0.5*(1-TMath::Erf(c1*pow(time,c2))) ;
   //return 0.5*(1+TMath::Erf(c1*time+c2)) ;
   //return 0.5*(1-exp(c1*time+c2*time*time));
 } 



