/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTagFunc.h" 
#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"

ClassImp(RooTagFunc) 

 RooTagFunc::RooTagFunc(const char *name, const char *title,
                            RooAbsCategory& _p,
                            RooAbsReal& _ACP, 
                            State _state) :
   RooAbsPdf(name,title),
   p("p","p",this,_p),
   ACP("ACP","ACP",this,_ACP),
   state(_state)
 {
 } 


 RooTagFunc::RooTagFunc(const RooTagFunc& other, const char* name) :  
   RooAbsPdf(other,name),
   p("p",this,other.p),
   ACP("ACP",this,other.ACP),
   state(other.state)
 { 
 } 



 Double_t RooTagFunc::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

   Double_t retVal = 0;
   if(state == KPI)
     retVal = 0.5*(1-p*ACP);
   else if(state == PIPI)
     retVal = (p == 0);
   else if(state == KK)
     retVal = (p == 2);

   return retVal;
 } 



 Int_t RooTagFunc::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   Int_t code = 0;
   if (matchArgs(allVars,analVars,p)) return 1 ; 
   return 0 ; 
 } 



 Double_t RooTagFunc::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x
   Double_t retVal = 0;
   if (code==1)  {
    if(state == KPI)
      retVal = 0.5*(1-ACP)+
               0.5*(1+ACP);
    else if(state == PIPI)
      retVal = 1;
    else if(state == KK)
      retVal = 1;
   }
   return retVal ; 

 } 



