/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTimePdfPhysNew2.h" 
#include "RooExponential.h"
#include "RooEffProd.h"
#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "Math/SpecFuncMathMore.h"
#include "Math/SpecFuncMathCore.h"
//#include "gsl/gsl_errno.h"

ClassImp(RooTimePdfPhysNew2) 

 RooTimePdfPhysNew2::RooTimePdfPhysNew2(const char *name, const char *title,
                            RooAbsCategory& _q,
                            RooKeysPdfSpecial& _pdfT,
                            RooKeysPdfSpecial& _pdfU) :
   RooAbsPdf(name,title),
   q("q","q",this,_q),
   pdfT("pdfT","pdfT",this,_pdfT),
   pdfU("pdfU","pdfU",this,_pdfU)
 {
 } 


 RooTimePdfPhysNew2::RooTimePdfPhysNew2(const RooTimePdfPhysNew2& other, const char* name) :  
   RooAbsPdf(other,name),
   q("q",this,other.q),
   pdfT("pdfT",this,other.pdfT),
   pdfU("pdfU",this,other.pdfU)
 {
 } 



 Double_t RooTimePdfPhysNew2::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

  Double_t retVal = 0;

  if     (q!=0) retVal = ((RooAbsPdf *) pdfT.absArg())->getVal(0);
  else if(q==0) retVal = ((RooAbsPdf *) pdfU.absArg())->getVal(0);
  else { printf("UNKNOWN VALUES OF Q\n"); exit(1); }
  //printf("EVALUATE BKG TIME %g\n",retVal);

  return retVal;

 } 


 Int_t RooTimePdfPhysNew2::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,  const char* rangeName) const
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   Int_t retValT = 0;
   Int_t retValU = 0;

   retValT = pdfT.arg().getAnalyticalIntegral(allVars,analVars,rangeName);
   retValU = pdfU.arg().getAnalyticalIntegral(allVars,analVars,rangeName);
  
   if(retValT!=retValU) printf("COGLIONE ROOTIMEPDFBKGNEW2\n"), exit(1);

   return retValT;

 } 

 Double_t RooTimePdfPhysNew2::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

  Double_t retVal = 0;
  if(code!=0) {
    if     (q!=0) retVal = pdfT.arg().analyticalIntegral(code,rangeName);
    else if(q==0) retVal = pdfU.arg().analyticalIntegral(code,rangeName);
    else { printf("UNKNOWN VALUES OF Q IN INTEGRATION\n"); exit(1); }
  }
 //printf("INTEGRAL BKG TIME %g\n",retVal);
 return retVal;

 } 



