/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTIMEPDFBKG
#define ROOTIMEPDFBKG

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "RooEffProd.h"
#include "TH1D.h"
 
class RooTimePdfBkg : public RooAbsPdf {
public:

  /// flags
  
  RooTimePdfBkg() {} ; 
  RooTimePdfBkg(const char *name, const char *title,
                RooAbsCategory& _q,
                RooAbsReal& _time,
                RooAbsReal& _c1T,
                RooAbsReal& _fracT,
                RooAbsReal& _alpha1T,
                RooAbsReal& _alpha2T,
                RooAbsReal& _c1U,
                RooAbsReal& _fracU,
                RooAbsReal& _alpha1U,
                RooAbsReal& _alpha2U);
  RooTimePdfBkg(const RooTimePdfBkg& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTimePdfBkg(*this,newname); }
  inline virtual ~RooTimePdfBkg() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooCategoryProxy q;
  RooRealProxy time;
  RooRealProxy c1T;
  RooRealProxy fracT;
  RooRealProxy alpha1T;
  RooRealProxy alpha2T;
  RooRealProxy c1U;
  RooRealProxy fracU;
  RooRealProxy alpha1U;
  RooRealProxy alpha2U;
  Double_t evaluate() const ;
  Double_t intProto(Double_t x, Double_t a, Double_t c) const;

private:

  ClassDef(RooTimePdfBkg,1) // Your description goes here...
};
 
#endif
