/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTIMEPDFBKGNEW2
#define ROOTIMEPDFBKGNEW2

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "RooEffProd.h"
#include "RooKeysPdfSpecial.h"
#include "TH1D.h"
 
class RooTimePdfBkgNew2 : public RooAbsPdf {
public:

  /// flags
  
  RooTimePdfBkgNew2() {} ; 
  RooTimePdfBkgNew2(const char *name, const char *title,
                   RooAbsCategory& _qi,
                   RooAbsCategory& _qj,
                   RooKeysPdfSpecial& _pdf11,
                   RooKeysPdfSpecial& _pdf10,
                   RooKeysPdfSpecial& _pdf01,
                   RooKeysPdfSpecial& _pdf00);
  RooTimePdfBkgNew2(const RooTimePdfBkgNew2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTimePdfBkgNew2(*this,newname); }
  inline virtual ~RooTimePdfBkgNew2() { }
  virtual Bool_t forceAnalyticalInt(const RooAbsArg& /*dep*/) const {
    return kTRUE ;
  }
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

   RooCategoryProxy qi;
   RooCategoryProxy qj;
   RooRealProxy pdf11;
   RooRealProxy pdf10;
   RooRealProxy pdf01;
   RooRealProxy pdf00; 
   Double_t evaluate() const;

private:

  ClassDef(RooTimePdfBkgNew2,1) // Your description goes here...
};
 
#endif
