/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTIMEPDFBKGNEW
#define ROOTIMEPDFBKGNEW

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "RooEffProd.h"
#include "TH1D.h"
 
class RooTimePdfBkgNew : public RooAbsPdf {
public:

  /// flags
  
  RooTimePdfBkgNew() {} ; 
  RooTimePdfBkgNew(const char *name, const char *title,
                   RooAbsCategory& _qi,
                   RooAbsCategory& _qj,
                   RooAbsReal& _time,
                   RooAbsReal& _c11,
                   RooAbsReal& _frac11,
                   RooAbsReal& _alpha1_11,
                   RooAbsReal& _alpha2_11,
                   RooAbsReal& _c10,
                   RooAbsReal& _frac10,
                   RooAbsReal& _alpha1_10,
                   RooAbsReal& _alpha2_10,
                   RooAbsReal& _c01,
                   RooAbsReal& _frac01,
                   RooAbsReal& _alpha1_01,
                   RooAbsReal& _alpha2_01,
                   RooAbsReal& _c00,
                   RooAbsReal& _frac00,
                   RooAbsReal& _alpha1_00,
                   RooAbsReal& _alpha2_00);
  RooTimePdfBkgNew(const RooTimePdfBkgNew& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTimePdfBkgNew(*this,newname); }
  inline virtual ~RooTimePdfBkgNew() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

   RooCategoryProxy qi;
   RooCategoryProxy qj;
   RooRealProxy time;
   RooRealProxy c11;
   RooRealProxy frac11;
   RooRealProxy alpha1_11;
   RooRealProxy alpha2_11;
   RooRealProxy c10;
   RooRealProxy frac10;
   RooRealProxy alpha1_10;
   RooRealProxy alpha2_10;
   RooRealProxy c01;
   RooRealProxy frac01;
   RooRealProxy alpha1_01;
   RooRealProxy alpha2_01;
   RooRealProxy c00;
   RooRealProxy frac00;
   RooRealProxy alpha1_00;
   RooRealProxy alpha2_00;
   Double_t evaluate() const;
   Double_t intProto(Double_t x, Double_t a, Double_t c) const;

private:

  ClassDef(RooTimePdfBkgNew,1) // Your description goes here...
};
 
#endif
