/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTIMEACCPDF
#define ROOTIMEACCPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooTimeAccPdf : public RooAbsPdf {
public:
  RooTimeAccPdf() {} ; 
  RooTimeAccPdf(const char *name, const char *title,
	      RooAbsReal& _time,
	      RooAbsReal& _c1,
	      RooAbsReal& _c2);
  RooTimeAccPdf(const RooTimeAccPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTimeAccPdf(*this,newname); }
  inline virtual ~RooTimeAccPdf() { }

protected:

  RooRealProxy time ;
  RooRealProxy c1 ;
  RooRealProxy c2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooTimeAccPdf,1) // Your description goes here...
};
 
#endif
