/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTimePdfBkgNew.h" 
#include "RooExponential.h"
#include "RooEffProd.h"
#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "Math/SpecFuncMathMore.h"
#include "Math/SpecFuncMathCore.h"
//#include "gsl/gsl_errno.h"

ClassImp(RooTimePdfBkgNew) 

 RooTimePdfBkgNew::RooTimePdfBkgNew(const char *name, const char *title,
                            RooAbsCategory& _qi,
                            RooAbsCategory& _qj,
                            RooAbsReal& _time,
                            RooAbsReal& _c11,
                            RooAbsReal& _frac11,
                            RooAbsReal& _alpha1_11,
                            RooAbsReal& _alpha2_11,
                            RooAbsReal& _c10,
                            RooAbsReal& _frac10,
                            RooAbsReal& _alpha1_10,
                            RooAbsReal& _alpha2_10,
                            RooAbsReal& _c01,
                            RooAbsReal& _frac01,
                            RooAbsReal& _alpha1_01,
                            RooAbsReal& _alpha2_01,
                            RooAbsReal& _c00,
                            RooAbsReal& _frac00,
                            RooAbsReal& _alpha1_00,
                            RooAbsReal& _alpha2_00) :
   RooAbsPdf(name,title),
   qi("qi","qi",this,_qi),
   qj("qj","qj",this,_qj),
   time("time","time",this,_time),
   c11("c11","c11",this,_c11),
   frac11("frac11","frac11",this,_frac11),
   alpha1_11("alpha1_11","alpha1_11",this,_alpha1_11),
   alpha2_11("alpha2_11","alpha2_11",this,_alpha2_11),
   c10("c10","c10",this,_c10),
   frac10("frac10","frac10",this,_frac10),
   alpha1_10("alpha1_10","alpha1_10",this,_alpha1_10),
   alpha2_10("alpha2_10","alpha2_10",this,_alpha2_10),
   c01("c01","c01",this,_c01),
   frac01("frac01","frac01",this,_frac01),
   alpha1_01("alpha1_01","alpha1_01",this,_alpha1_01),
   alpha2_01("alpha2_01","alpha2_01",this,_alpha2_01),
   c00("c00","c00",this,_c00),
   frac00("frac00","frac00",this,_frac00),
   alpha1_00("alpha1_00","alpha1_00",this,_alpha1_00),
   alpha2_00("alpha2_00","alpha2_00",this,_alpha2_00)   
 {
   //  gsl_set_error_handler_off();
 } 


 RooTimePdfBkgNew::RooTimePdfBkgNew(const RooTimePdfBkgNew& other, const char* name) :  
   RooAbsPdf(other,name),
   qi("qi",this,other.qi),
   qj("qj",this,other.qj),
   time("time",this,other.time),
   c11("c11",this,other.c11),
   frac11("frac11",this,other.frac11),
   alpha1_11("alpha1_11",this,other.alpha1_11),
   alpha2_11("alpha2_11",this,other.alpha2_11),
   c10("c10",this,other.c10),
   frac10("frac10",this,other.frac10),
   alpha1_10("alpha1_10",this,other.alpha1_10),
   alpha2_10("alpha2_10",this,other.alpha2_10),
   c01("c01",this,other.c01),
   frac01("frac01",this,other.frac01),
   alpha1_01("alpha1_01",this,other.alpha1_01),
   alpha2_01("alpha2_01",this,other.alpha2_01),
   c00("c00",this,other.c00),
   frac00("frac00",this,other.frac00),
   alpha1_00("alpha1_00",this,other.alpha1_00),
   alpha2_00("alpha2_00",this,other.alpha2_00)
 { 
 } 



 Double_t RooTimePdfBkgNew::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

  Double_t exp11 = frac11*alpha1_11*exp(alpha1_11*time)/(exp(alpha1_11*time.max())-exp(alpha1_11*time.min()))+
                   (1-frac11)*alpha2_11*exp(alpha2_11*time)/(exp(alpha2_11*time.max())-exp(alpha2_11*time.min()));
  Double_t exp01 = frac01*alpha1_01*exp(alpha1_01*time)/(exp(alpha1_01*time.max())-exp(alpha1_01*time.min()))+
                   (1-frac01)*alpha2_01*exp(alpha2_01*time)/(exp(alpha2_01*time.max())-exp(alpha2_01*time.min()));
  Double_t exp10 = frac10*alpha1_10*exp(alpha1_10*time)/(exp(alpha1_10*time.max())-exp(alpha1_10*time.min()))+
                   (1-frac10)*alpha2_10*exp(alpha2_10*time)/(exp(alpha2_10*time.max())-exp(alpha2_10*time.min()));
  Double_t exp00 = frac00*alpha1_00*exp(alpha1_00*time)/(exp(alpha1_00*time.max())-exp(alpha1_00*time.min()))+
                   (1-frac00)*alpha2_00*exp(alpha2_00*time)/(exp(alpha2_00*time.max())-exp(alpha2_00*time.min()));

//  Double_t accT = (1+erf(c1T*time+c2T));
//  Double_t accU = (1+erf(c1U*time+c2U));

//  Double_t accT = (1+erf(c1T-c1T*time));
//  Double_t accU = (1+erf(c1U-c1U*time));

  Double_t acc11 = (1+tanh(c11-c11*time));
  Double_t acc01 = (1+tanh(c01-c01*time));
  Double_t acc10 = (1+tanh(c10-c10*time));
  Double_t acc00 = (1+tanh(c00-c00*time));

  Double_t retVal;

  if     (qi!=0&&qj!=0) retVal = acc11*exp11;
  else if(qi!=0&&qj==0) retVal = acc10*exp10;
  else if(qi==0&&qj!=0) retVal = acc01*exp01;
  else if(qi==0&&qj==0) retVal = acc00*exp00;
  else { printf("UNKNOWN VALUES OF Q\n"); exit(1); }

  return retVal;

 } 



 Int_t RooTimePdfBkgNew::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,  const char* rangeName) const
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   if(matchArgs(allVars,analVars,time)) return 1;
   return 0;

 } 

 Double_t RooTimePdfBkgNew::intProto(Double_t x, Double_t a, Double_t c) const {

   
//   Double_t ret = -exp((c*(c-4*a*b))/(4*a*a))*erf(-c/2/a + a*x + b)+
//                   exp(c*x)*erf(a*x+b)+exp(c*x);

//   Double_t ret = -exp((c*(c+4*a*a))/(4*a*a))*erf(c/2/a + -a*x + a)+
//                   exp(c*x)*erf(-a*x+a)+exp(c*x);

   Double_t ret;
   Double_t hg;

   //printf("a=%g c=%g x=%g\n",a,c,x);

   Double_t z = -TMath::Exp(2*a*(x-1));

   //printf("z=%g 1/(1-z)=%g\n",z,1/(1-z));

   Double_t cd2da = c/2/a;

   if(z>-0.5) {
     hg = ROOT::Math::hyperg(1, cd2da, cd2da+1, z);
   } else {
     Double_t gb = ROOT::Math::tgamma(cd2da);
     Double_t gc = cd2da*gb; // Gamma(cd2da+1)
     Double_t gbma = gb/(cd2da-1); // Gamma(cd2da-1)
     Double_t gcma = gb;
     Double_t gamb = TMath::Pi()/sin(TMath::Pi()*cd2da)/gb; // Gamma(1-cd2da)

     hg = 1/(1-z)*gc*gbma/gb/gcma*
          ROOT::Math::hyperg(1, 1, 2-cd2da, 1/(1-z))+
          TMath::Power(1-z,-cd2da)*gc*gamb*
          ROOT::Math::hyperg(cd2da, cd2da, cd2da, 1/(1-z));
   }

   ret = 2*exp(c*x)*hg;

   //printf("hyperg=%g ret=%g\n",hg, ret);

   //printf("INSIDE INTPROTO %g %g %g %g %g\n",x,a,b,c,ret);
   return ret;
 }


 Double_t RooTimePdfBkgNew::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

  Double_t K1_11 = (exp(alpha1_11*time.max())-exp(alpha1_11*time.min()));
  Double_t K2_11 = (exp(alpha2_11*time.max())-exp(alpha2_11*time.min()));
  Double_t K1_10 = (exp(alpha1_10*time.max())-exp(alpha1_10*time.min()));
  Double_t K2_10 = (exp(alpha2_10*time.max())-exp(alpha2_10*time.min()));
  Double_t K1_01 = (exp(alpha1_01*time.max())-exp(alpha1_01*time.min()));
  Double_t K2_01 = (exp(alpha2_01*time.max())-exp(alpha2_01*time.min()));
  Double_t K1_00 = (exp(alpha1_00*time.max())-exp(alpha1_00*time.min()));
  Double_t K2_00 = (exp(alpha2_00*time.max())-exp(alpha2_00*time.min()));

  Double_t int1Max_11 = intProto(time.max(),c11,alpha1_11)/K1_11;
  Double_t int2Max_11 = intProto(time.max(),c11,alpha2_11)/K2_11;
  Double_t int1Min_11 = intProto(time.min(),c11,alpha1_11)/K1_11;
  Double_t int2Min_11 = intProto(time.min(),c11,alpha2_11)/K2_11;

  Double_t int1Max_10 = intProto(time.max(),c10,alpha1_10)/K1_10;
  Double_t int2Max_10 = intProto(time.max(),c10,alpha2_10)/K2_10;
  Double_t int1Min_10 = intProto(time.min(),c10,alpha1_10)/K1_10;
  Double_t int2Min_10 = intProto(time.min(),c10,alpha2_10)/K2_10;

  Double_t int1Max_01 = intProto(time.max(),c01,alpha1_01)/K1_01;
  Double_t int2Max_01 = intProto(time.max(),c01,alpha2_01)/K2_01;
  Double_t int1Min_01 = intProto(time.min(),c01,alpha1_01)/K1_01;
  Double_t int2Min_01 = intProto(time.min(),c01,alpha2_01)/K2_01;

  Double_t int1Max_00 = intProto(time.max(),c00,alpha1_00)/K1_00;
  Double_t int2Max_00 = intProto(time.max(),c00,alpha2_00)/K2_00;
  Double_t int1Min_00 = intProto(time.min(),c00,alpha1_00)/K1_00;
  Double_t int2Min_00 = intProto(time.min(),c00,alpha2_00)/K2_00;


  Double_t retVal11 = frac11*(int1Max_11-int1Min_11)+(1-frac11)*(int2Max_11-int2Min_11);
  Double_t retVal10 = frac10*(int1Max_10-int1Min_10)+(1-frac10)*(int2Max_10-int2Min_10);
  Double_t retVal01 = frac01*(int1Max_01-int1Min_01)+(1-frac01)*(int2Max_01-int2Min_01);
  Double_t retVal00 = frac00*(int1Max_00-int1Min_00)+(1-frac00)*(int2Max_00-int2Min_00);

  if(code==1) {
    if     (qi!=0&&qj!=0) return frac11*(int1Max_11-int1Min_11)+(1-frac11)*(int2Max_11-int2Min_11);
    else if(qi!=0&&qj==0) return frac10*(int1Max_10-int1Min_10)+(1-frac10)*(int2Max_10-int2Min_10);
    else if(qi==0&&qj!=0) return frac01*(int1Max_01-int1Min_01)+(1-frac01)*(int2Max_01-int2Min_01);
    else if(qi==0&&qj==0) return frac00*(int1Max_00-int1Min_00)+(1-frac00)*(int2Max_00-int2Min_00);
    else { printf("UNKNOWN VALUES OF Q IN INTEGRATION\n"); exit(1); }
  }
  return 0;


 } 



