/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTimePdfBkgNew2.h" 
#include "RooExponential.h"
#include "RooEffProd.h"
#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "Math/SpecFuncMathMore.h"
#include "Math/SpecFuncMathCore.h"
#include "gsl/gsl_errno.h"

ClassImp(RooTimePdfBkgNew2) 

 RooTimePdfBkgNew2::RooTimePdfBkgNew2(const char *name, const char *title,
                            RooAbsCategory& _qi,
                            RooAbsCategory& _qj,
                            RooKeysPdfSpecial& _pdf11,
                            RooKeysPdfSpecial& _pdf10,
                            RooKeysPdfSpecial& _pdf01,
                            RooKeysPdfSpecial& _pdf00) :
   RooAbsPdf(name,title),
   qi("qi","qi",this,_qi),
   qj("qj","qj",this,_qj),
   pdf11("pdf11","pdf11",this,_pdf11),
   pdf10("pdf10","pdf10",this,_pdf10),
   pdf01("pdf01","pdf01",this,_pdf01),
   pdf00("pdf00","pdf00",this,_pdf00)
 {
 } 


 RooTimePdfBkgNew2::RooTimePdfBkgNew2(const RooTimePdfBkgNew2& other, const char* name) :  
   RooAbsPdf(other,name),
   qi("qi",this,other.qi),
   qj("qj",this,other.qj),
   pdf11("pdf11",this,other.pdf11),
   pdf10("pdf10",this,other.pdf10),
   pdf01("pdf01",this,other.pdf01),
   pdf00("pdf00",this,other.pdf00)
 {
 } 



 Double_t RooTimePdfBkgNew2::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

  Double_t retVal = 0;

  if     (qi!=0&&qj!=0) retVal = ((RooAbsPdf *) pdf11.absArg())->getVal(0);
  else if(qi!=0&&qj==0) retVal = ((RooAbsPdf *) pdf10.absArg())->getVal(0);
  else if(qi==0&&qj!=0) retVal = ((RooAbsPdf *) pdf01.absArg())->getVal(0);
  else if(qi==0&&qj==0) retVal = ((RooAbsPdf *) pdf00.absArg())->getVal(0);
  else { printf("UNKNOWN VALUES OF Q\n"); exit(1); }
  //printf("EVALUATE BKG TIME %g\n",retVal);

  return retVal;

 } 


 Int_t RooTimePdfBkgNew2::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,  const char* rangeName) const
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   Int_t retVal11 = 0;
   Int_t retVal10 = 0;
   Int_t retVal01 = 0;
   Int_t retVal00 = 0;

   retVal11 = pdf11.arg().getAnalyticalIntegral(allVars,analVars,rangeName);
   retVal10 = pdf10.arg().getAnalyticalIntegral(allVars,analVars,rangeName);
   retVal01 = pdf01.arg().getAnalyticalIntegral(allVars,analVars,rangeName);
   retVal00 = pdf00.arg().getAnalyticalIntegral(allVars,analVars,rangeName);
  
   if(retVal11!=retVal10||retVal10!=retVal01||retVal01!=retVal00) printf("COGLIONE ROOTIMEPDFBKGNEW2\n"), exit(1);

   return retVal11;

 } 

 Double_t RooTimePdfBkgNew2::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

  Double_t retVal = 0;
  if(code!=0) {
    if     (qi!=0&&qj!=0) retVal = pdf11.arg().analyticalIntegral(code,rangeName);
    else if(qi!=0&&qj==0) retVal = pdf10.arg().analyticalIntegral(code,rangeName);
    else if(qi==0&&qj!=0) retVal = pdf01.arg().analyticalIntegral(code,rangeName);
    else if(qi==0&&qj==0) retVal = pdf00.arg().analyticalIntegral(code,rangeName);
    else { printf("UNKNOWN VALUES OF Q IN INTEGRATION\n"); exit(1); }
  }
 //printf("INTEGRAL BKG TIME %g\n",retVal);
 return retVal;

 } 



