/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTIMEPDFPHYSNEW
#define ROOTIMEPDFPHYSNEW

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "RooEffProd.h"
#include "TH1D.h"
 
class RooTimePdfPhysNew : public RooAbsPdf {
public:

  /// flags
  
  RooTimePdfPhysNew() {} ; 
  RooTimePdfPhysNew(const char *name, const char *title,
                            RooAbsCategory& _q,
                            RooAbsReal& _time,
                            RooAbsReal& _c0,
                            RooAbsReal& _b0,
                            RooAbsReal& _a0,
                            RooAbsReal& _c1,
                            RooAbsReal& _b1,
                            RooAbsReal& _a1,
                            RooAbsReal& _G);
  RooTimePdfPhysNew(const RooTimePdfPhysNew& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTimePdfPhysNew(*this,newname); }
  inline virtual ~RooTimePdfPhysNew() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

   RooCategoryProxy q;
   RooRealProxy time;
   RooRealProxy c0;
   RooRealProxy b0;
   RooRealProxy a0;
   RooRealProxy c1;
   RooRealProxy b1;
   RooRealProxy a1;
   RooRealProxy G;
   Double_t evaluate() const;
   Double_t intProto(Double_t x, Double_t a, Double_t b, Double_t c, Double_t G) const;

private:

  ClassDef(RooTimePdfPhysNew,1) // Your description goes here...
};
 
#endif
