/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTIMEPDFPHYSNEW2
#define ROOTIMEPDFPHYSNEW2

#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsCategory.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "RooEffProd.h"
#include "RooKeysPdfSpecial.h"
#include "TH1D.h"
 
class RooTimePdfPhysNew2 : public RooAbsPdf {
public:

  /// flags
  
  RooTimePdfPhysNew2() {} ; 
  RooTimePdfPhysNew2(const char *name, const char *title,
                   RooAbsCategory& _q,
                   RooKeysPdfSpecial& _pdfT,
                   RooKeysPdfSpecial& _pdfU);
  RooTimePdfPhysNew2(const RooTimePdfPhysNew2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTimePdfPhysNew2(*this,newname); }
  inline virtual ~RooTimePdfPhysNew2() { }
  virtual Bool_t forceAnalyticalInt(const RooAbsArg& /*dep*/) const {
    return kTRUE ;
  }
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

   RooCategoryProxy q;
   RooRealProxy pdfT;
   RooRealProxy pdfU;
   Double_t evaluate() const;

private:

  ClassDef(RooTimePdfPhysNew2,1) // Your description goes here...
};
 
#endif
