/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTimePdfPhysNew.h" 
#include "RooExponential.h"
#include "RooEffProd.h"
#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"
#include "Math/SpecFuncMathMore.h"
#include "Math/SpecFuncMathCore.h"
#include "gsl/gsl_errno.h"

ClassImp(RooTimePdfPhysNew) 

 RooTimePdfPhysNew::RooTimePdfPhysNew(const char *name, const char *title,
                            RooAbsCategory& _q,
                            RooAbsReal& _time,
                            RooAbsReal& _c0,
                            RooAbsReal& _b0,
                            RooAbsReal& _a0,
                            RooAbsReal& _c1,
                            RooAbsReal& _b1,
                            RooAbsReal& _a1,
                            RooAbsReal& _G) :
   RooAbsPdf(name,title),
   q("q","q",this,_q),
   time("time","time",this,_time),
   c0("c0","c0",this,_c0),
   b0("b0","b0",this,_b0),
   a0("a0","a0",this,_a0),
   c1("c1","c1",this,_c1),
   b1("b1","b1",this,_b1),
   a1("a1","a1",this,_a1),
   G("G","G",this,_G)
 {
  gsl_set_error_handler_off();
 } 


 RooTimePdfPhysNew::RooTimePdfPhysNew(const RooTimePdfPhysNew& other, const char* name) :  
   RooAbsPdf(other,name),
   q("q",this,other.q),
   time("time",this,other.time),
   c0("c0",this,other.c0),
   b0("b0",this,other.b0),
   a0("a0",this,other.a0),
   c1("c1",this,other.c1),
   b1("b1",this,other.b1),
   a1("a1",this,other.a1),
   G("G",this,other.G)
 { 
 } 



 Double_t RooTimePdfPhysNew::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

  Double_t K0 = a0-G;
  Double_t K1 = a1-G;

  Double_t f0 = exp(-G*time)+c0*time*exp(-G*time)-exp(K0*time-b0*time*time)-c0*time*exp(K0*time-b0*time*time);
  Double_t f1 = exp(-G*time)+c1*time*exp(-G*time)-exp(K1*time-b1*time*time)-c1*time*exp(K1*time-b1*time*time);

  Double_t retVal = q == 0 ? f0 : f1;
  return retVal;

 } 



 Int_t RooTimePdfPhysNew::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,  const char* rangeName) const
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   if(matchArgs(allVars,analVars,time)) return 1;
   return 0;

 } 

 Double_t RooTimePdfPhysNew::intProto(Double_t x, Double_t a, Double_t b, Double_t c, Double_t G) const {

  Double_t K = a-G;
  Double_t sqPi = sqrt(TMath::Pi());
  Double_t sqB = sqrt(b);
  Double_t Int1 = -exp(-G*x)/G;

  Double_t Int2 = -c*exp(-G*x)*(G*x+1)/G/G;

  Double_t Int3 = 0.5*(sqPi*exp(0.25*K*K/b)*erf(0.5*(K-2*b*x)/sqB))/sqB;

  Double_t Int4 = -c*( 0.25*(sqPi*exp(0.25*K*K/b)*erf(0.5*(2*b*x-K)/sqB))/sqrt(b*b*b) - 
                      0.5*exp(K*x-b*x*x)/b );

  return Int1+Int2+Int3+Int4;

 }


 Double_t RooTimePdfPhysNew::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

  Double_t tMax = time.max(); Double_t tMin = time.min();

  Double_t retValMax0 = intProto(tMax,a0,b0,c0,G);
  Double_t retValMin0 = intProto(tMin,a0,b0,c0,G);
  Double_t retValMax1 = intProto(tMax,a1,b1,c1,G);
  Double_t retValMin1 = intProto(tMin,a1,b1,c1,G);

  Double_t retVal = q == 0 ? (retValMax0-retValMin0) :
                             (retValMax1-retValMin1);
  return retVal;

 } 



