/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTagFuncNew.h" 
#include "RooAbsReal.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "RooHistPdf.h"
#include "RooDataHist.h"

ClassImp(RooTagFuncNew) 

 RooTagFuncNew::RooTagFuncNew(const char *name, const char *title,
                            RooAbsCategory& _p,
                            RooAbsCategory& _qi,
                            RooAbsCategory& _qj,
                            RooAbsReal& _ACP, 
                            RooAbsReal& _Atagi, 
                            RooAbsReal& _Atagj, 
                            State _state) :
   RooAbsPdf(name,title),
   p("p","p",this,_p),
   qi("qi","qi",this,_qi),
   qj("qj","qj",this,_qj),
   ACP("ACP","ACP",this,_ACP),
   Atagi("Atagi","Atagi",this,_Atagi),
   Atagj("Atagj","Atagj",this,_Atagj),
   state(_state)
 {
 } 


 RooTagFuncNew::RooTagFuncNew(const RooTagFuncNew& other, const char* name) :  
   RooAbsPdf(other,name),
   p("p",this,other.p),
   qi("qi",this,other.qi),
   qj("qj",this,other.qj),
   ACP("ACP",this,other.ACP),
   Atagi("Atagi",this,other.Atagi),
   Atagj("Atagj",this,other.Atagj),
   state(other.state)
 { 
 } 



 Double_t RooTagFuncNew::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

   Double_t retVal = 0;
   if(state == KPI)
     retVal = 0.5*(1-p*ACP)*(1-p*qi*Atagi)*(1-p*qj*Atagj);
   else if(state == PIPI)
     retVal = (p == 0);
   else if(state == KK)
     retVal = (p == 2);

   return retVal;
 } 



 Int_t RooTagFuncNew::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   Int_t code = 0;
   if (matchArgs(allVars,analVars,p)) return 1 ; 
   return 0 ; 
 } 



 Double_t RooTagFuncNew::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x
   Double_t retVal = 0;
   if (code==1)  {
    if(state == KPI)
      retVal = 0.5*(1-ACP)*(1-qi*Atagi)*(1-qj*Atagj)+
               0.5*(1+ACP)*(1+qi*Atagi)*(1+qj*Atagj);
    else if(state == PIPI)
      retVal = 1;
    else if(state == KK)
      retVal = 1;
   }
   return retVal ; 

 } 



