/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTIMEACCPHYSPDF
#define ROOTIMEACCPHYSPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooTimeAccPhysPdf : public RooAbsPdf {
public:
  RooTimeAccPhysPdf() {} ; 
  RooTimeAccPhysPdf(const char *name, const char *title,
	      RooAbsReal& _time,
	      RooAbsReal& _c1,
	      RooAbsReal& _c2,
	      RooAbsReal& _c3);
  RooTimeAccPhysPdf(const RooTimeAccPhysPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTimeAccPhysPdf(*this,newname); }
  inline virtual ~RooTimeAccPhysPdf() { }

protected:

  RooRealProxy time ;
  RooRealProxy c1 ;
  RooRealProxy c2 ;
  RooRealProxy c3 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooTimeAccPhysPdf,1) // Your description goes here...
};
 
#endif
