/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...
#ifndef sel_ROOJOHNSONFUNC_cxx
#define sel_ROOJOHNSONFUNC_cxx
#include "Riostream.h"

#include "sel_RooJohnsonFunc.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

ClassImp(sel_RooJohnsonFunc)

 sel_RooJohnsonFunc::sel_RooJohnsonFunc(const char *name, const char *title,
                        RooAbsReal& _mass,
                        RooAbsReal& _mean,
                        RooAbsReal& _sigma1,
                        RooAbsReal& _alpha1,
                        RooAbsReal& _alpha2) :
   RooAbsPdf(name,title), 
   mass("mass","mass",this,_mass),
   mean("mean","mean",this,_mean),
   sigma1("sigma1","sigma1",this,_sigma1),
   alpha1("alpha1","alpha1",this,_alpha1),
   alpha2("alpha2","alpha2",this,_alpha2)
 {
 }


 sel_RooJohnsonFunc::sel_RooJohnsonFunc(const sel_RooJohnsonFunc& other, const char* name) :
   RooAbsPdf(other,name),
   mass("mass",this,other.mass),
   mean("mean",this,other.mean),
   sigma1("sigma1",this,other.sigma1),
   alpha1("alpha1",this,other.alpha1),
   alpha2("alpha2",this,other.alpha2)
 {
 }



 Double_t sel_RooJohnsonFunc::evaluate() const
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
   Double_t arg = (mass-mean)/sigma1;
   Double_t expo = alpha1+alpha2*asinh(arg);
   Double_t retVal = exp(-0.5*expo*expo)/sqrt(1+arg*arg);
   return  retVal; 
 }



 Int_t sel_RooJohnsonFunc::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* /*rangeName*/) const
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED,
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs
   // EXPRESSION MULTIPLE TIMES

   if (matchArgs(allVars,analVars,mass)) return 1 ;
   return 0 ;
 }



 Double_t sel_RooJohnsonFunc::analyticalIntegral(Int_t code, const char* rangeName) const
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   if(code==1) {

     Double_t argMax = (mean-mass.max(rangeName))/sigma1;
     Double_t argMin = (mean-mass.min(rangeName))/sigma1;
     Double_t maxVal = sqrt(M_PI_2)*sigma1*erf(M_SQRT1_2*alpha1-M_SQRT1_2*alpha2*asinh(argMax))/alpha2;
     Double_t minVal = sqrt(M_PI_2)*sigma1*erf(M_SQRT1_2*alpha1-M_SQRT1_2*alpha2*asinh(argMin))/alpha2;

     return maxVal-minVal;
   }
   return 0 ;
 }

#endif