/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

 #ifndef sel_ROOJOHNSONFUNC
 #define sel_ROOJOHNSONFUNC
 
 #include "RooAbsPdf.h"
 #include "RooRealProxy.h"
 #include "RooCategoryProxy.h"
 #include "RooAbsReal.h"
 #include "RooAbsCategory.h"
  
 class sel_RooJohnsonFunc : public RooAbsPdf {
 public:
   sel_RooJohnsonFunc() {} ; 
   sel_RooJohnsonFunc(const char *name, const char *title,
           RooAbsReal& _mass,
           RooAbsReal& _mean,
           RooAbsReal& _sigma1,
           RooAbsReal& _alpha1,
           RooAbsReal& _alpha2);
   sel_RooJohnsonFunc(const sel_RooJohnsonFunc& other, const char* name=0) ;
   virtual TObject* clone(const char* newname) const { return new sel_RooJohnsonFunc(*this,newname); }
   inline virtual ~sel_RooJohnsonFunc() { }
 
   Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
   Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
 
 protected:
 
   RooRealProxy mass ;
   RooRealProxy mean ;
   RooRealProxy sigma1 ;
   RooRealProxy alpha1 ;
   RooRealProxy alpha2 ;
   
   Double_t evaluate() const ;
 
 private:
 
   ClassDef(sel_RooJohnsonFunc,1) // Your description goes here...
 };
  
 #endif