import ROOT
from ROOT import RooFit
plotOpts201516 = { 
        "KPI_201516"  : { 'E' : { 'components' : 'bkg_kpi_pdf_201516',
                                'color'      : [171./255,221./255,164./255],#RooFit.kGray,
                                'fill'       : 1001,
                                'name'       : 'bkg',
                                'plotName'   : 'Comb. bkg.' },
                        'D' : { 'components' : "bkg_kpi_pdf_201516,phys_kpi1_pdf_201516,phys_kpi2_pdf_201516",
                                'color'      : [215./255,25./255,28./255],#RooFit.kGray+1,
                                'fill'       : 1001,
                                'name'       : '3body',
                                'plotName'   : '3-Body bkg.' },
                        'C' : { 'components' : "bkg_kpi_pdf_201516,phys_kpi1_pdf_201516,phys_kpi2_pdf_201516,bdpipi_kpi_pdf_201516,bskk_kpi_pdf_201516",
                                'color'      : [253./255,174./255,97./255],#RooFit.kGray+2,
                                'fill'       : 1001,
                                'name'       : 'cross-feed',
                                'plotName'   : '#splitline{#it{B}^{0}_{#it{s}}#rightarrow#it{K}^{ +}#it{K}^{ #minus},}{#it{B}^{0}#rightarrow#it{#pi}^{ +}#it{#pi}^{ #minus}}' },
                        
                        'B' : { 'components' : "bkg_kpi_pdf_201516,phys_kpi1_pdf_201516,phys_kpi2_pdf_201516,bskpi_pdf_201516",
                                'color'      : [43./255,131./255,186./255],#RooFit.kGray+3,
                                'fill'       : 1001,
                                'name'       : 'bskpi',
                                'plotName'   : '#it{#bar{B}}^{0}_{#it{s}}#rightarrow#it{K}^{ +}#it{#pi}^{ #minus}' },
                        'A' : { 'components' : "bkg_kpi_pdf_201516,phys_kpi1_pdf_201516,phys_kpi2_pdf_201516,bskpi_pdf_201516,bdkpi_pdf_201516",
                                'color'      : RooFit.kBlack,
                                'fill'       : 0,
                                'name'       : 'total',
                                'plotName'   : '#it{B}^{0}#rightarrow#it{K}^{ +}#it{#pi}^{ #minus}' },
                        },
        "PIPI_201516" : { 'E' : { 'components' : 'bkg_pipi_pdf_201516',
                                'color'      : [171./255,221./255,164./255],#RooFit.kGray,
                                'fill'       : 1001,
                                'name'       : 'bkg',
                                'plotName'   : 'Comb. bkg.' },
                        'D' : { 'components' : "bkg_pipi_pdf_201516,phys_pipi_pdf_201516",
                                'color'      : [215./255,25./255,28./255],#RooFit.kGray+1,
                                'fill'       : 1001,
                                'name'       : '3body',
                                'plotName'   : '3-Body bkg.' },
                        'C' : { 'components' : "bkg_pipi_pdf_201516,phys_pipi_pdf_201516,bdkpi_pipi_pdf_201516",
                                'color'      : [253./255,174./255,97./255],#RooFit.kGray+2,
                                'fill'       : 1001,
                                'name'       : 'bdkpi',
                                'plotName'   : '#it{B}^{0}#rightarrow#it{K}^{ +}#it{#pi}^{ #minus}' },
                        'B' : { 'components' : "bkg_pipi_pdf_201516,phys_pipi_pdf_201516,bdkpi_pipi_pdf_201516,bspipi_pdf_201516",
                                'color'      : [43./255,131./255,186./255],#RooFit.kGray+3,
                                'fill'       : 1001,
                                'name'       : 'bspipi',
                                'plotName'   : '#it{B}^{0}_{#it{s}}#rightarrow#it{#pi}^{ +}#it{#pi}^{ #minus}'  },
                        
                        'A' : { 'components' : "bkg_pipi_pdf_201516,phys_pipi_pdf_201516,bdkpi_pipi_pdf_201516,bspipi_pdf_201516,bdpipi_pdf_201516",
                                'color'      : RooFit.kBlack,
                                'fill'       : 0,
                                'name'       : 'total',
                                'plotName'   : '#it{B}^{0}#rightarrow#it{#pi}^{ +}#it{#pi}^{ #minus}' },
                        },
        "KK_201516"   : { 
                'E' : { 'components' : 'bkg_kk_pdfmass_201516',
                                'color'      : [171./255,221./255,164./255],#RooFit.kGray,
                                'fill'       : 1001,
                                'name'       : 'bkg',
                                'plotName'   : 'Comb. bkg.' },
                        'D' : { 'components' : 'bkg_kk_pdfmass_201516,phys_kk_pdfmass_201516',
                                'color'      : [215./255,25./255,28./255],#RooFit.kGray+1,
                                'fill'       : 1001,
                                'name'       : '3body',
                                'plotName'   : '3-Body bkg.' },
                        'C' : { 'components' : "bkg_kk_pdfmass_201516,phys_kk_pdfmass_201516,bdkk_pdfmass_201516,lbpk_kk_pdfmass_201516",
                                'color'      : (253./255,174./255,97./255),#RooFit.kGray+2,
                                'fill'       : 1001,
                                'name'       : 'lbpk',
                                'plotName'   : '#splitline{#Lambda^{0}_{#it{b}}#rightarrow#it{p}#it{K}^{ #minus},}{#it{B}^{0}#rightarrow#it{K}^{ +}#it{K}^{ #minus}}' },
                        'B' : { 'components' : "bkg_kk_pdfmass_201516,phys_kk_pdfmass_201516,bdkk_pdfmass_201516,lbpk_kk_pdfmass_201516,bdkpi_kk_pdfmass_201516",
                                'color'      : [43./255,131./255,186./255],#RooFit.kGray+3,
                                'fill'       : 1001,
                                'name'       : 'bdkpi',
                                'plotName'   : '#it{B}^{0}#rightarrow#it{K}^{ +}#it{#pi}^{ #minus}' },
                        'A' : { 'components' : "bkg_kk_pdfmass_201516,phys_kk_pdfmass_201516,bdkk_pdfmass_201516,lbpk_kk_pdfmass_201516,bdkpi_kk_pdfmass_201516,bskk_pdfmass_201516",
                                'color'      : RooFit.kBlack,
                                'fill'       : 0,
                                'name'       : 'total',
                                'plotName'   : '#it{B}^{0}_{#it{s}}#rightarrow#it{K}^{ +}#it{K}^{ #minus}' },
                        },
}
