import ROOT
from ROOT import RooFit ##62 instances of pdfmass became pdf
plotOptsTot = { 
        "KPI_Tot"  : { 'E' : { 'components' : 'bkg_kpi_pdf_Tot',
                                'color'      : [171./255,221./255,164./255],#RooFit.kGray,
                                'fill'       : 1001,
                                'name'       : 'bkg',
                                'plotName'   : 'Comb. bkg.' },
                        'D' : { 'components' : "bkg_kpi_pdf_Tot,phys_kpi1_pdf_Tot,phys_kpi2_pdf_Tot",
                                'color'      : [215./255,25./255,28./255],#RooFit.kGray+1,
                                'fill'       : 1001,
                                'name'       : '3body',
                                'plotName'   : '3-Body bkg.' },
                        'C' : { 'components' : "bkg_kpi_pdf_Tot,phys_kpi1_pdf_Tot,phys_kpi2_pdf_Tot,bdpipi_kpi_pdf_Tot,bskk_kpi_pdf_Tot",
                                'color'      : [253./255,174./255,97./255],#RooFit.kGray+2,
                                'fill'       : 1001,
                                'name'       : 'cross-feed',
                                'plotName'   : '#splitline{#it{B}^{0}_{#it{s}}#rightarrow#it{K}^{ +}#it{K}^{ #minus},}{#it{B}^{0}#rightarrow#it{#pi}^{ +}#it{#pi}^{ #minus}}' },
                        
                        'B' : { 'components' : "bkg_kpi_pdf_Tot,phys_kpi1_pdf_Tot,phys_kpi2_pdf_Tot,bskpi_pdf_Tot",
                                'color'      : [43./255,131./255,186./255],#RooFit.kGray+3,
                                'fill'       : 1001,
                                'name'       : 'bskpi',
                                'plotName'   : '#it{#bar{B}}^{0}_{#it{s}}#rightarrow#it{K}^{ +}#it{#pi}^{ #minus}' },
                        'A' : { 'components' : "bkg_kpi_pdf_Tot,phys_kpi1_pdf_Tot,phys_kpi2_pdf_Tot,bskpi_pdf_Tot,bdkpi_pdf_Tot",
                                'color'      : RooFit.kBlack,
                                'fill'       : 0,
                                'name'       : 'total',
                                'plotName'   : '#it{B}^{0}#rightarrow#it{K}^{ +}#it{#pi}^{ #minus}' },
                        },
           "PIPI_Tot" : {
                        'F' : { 'components' : 'bkg_pipi_pdf_Tot',
                                'color'      : [171./255,221./255,164./255],#RooFit.kGray,
                                'fill'       : 1001,
                                'name'       : 'bkg',
                                'plotName'   : 'Comb. bkg.' },
                        'E' : { 'components' : "bkg_pipi_pdf_Tot,phys_pipi_pdf_Tot",
                                'color'      : [215./255,25./255,28./255],#RooFit.kGray+1,
                                'fill'       : 1001,
                                'name'       : '3body',
                                'plotName'   : '3-Body bkg.' },
                        'D' : { 'components' : 'bkg_pipi_pdf_Tot,phys_pipi_pdf_Tot,bskpi_pipi_pdf_Tot',
                                'color'      : [1./255,254./255,254./255],#RooFit.kGray,
                                'fill'       : 1001,
                                'name'       : 'bskpi',
                                'plotName'   : '#it{B}^{0}_{#it{s}}#rightarrow#it{#pi}^{ +}#it{K}^{ #minus}'  },
                        'C' : { 'components' : "bkg_pipi_pdf_Tot,phys_pipi_pdf_Tot,bdkpi_pipi_pdf_Tot,bskpi_pipi_pdf_Tot",
                                'color'      : [253./255,174./255,97./255],#RooFit.kGray+2,
                                'fill'       : 1001,
                                'name'       : 'bdkpi',
                                'plotName'   : '#it{B}^{0}#rightarrow#it{K}^{ +}#it{#pi}^{ #minus}' },
                        'B' : { 'components' : "bkg_pipi_pdf_Tot,phys_pipi_pdf_Tot,bdkpi_pipi_pdf_Tot,bspipi_pdf_Tot,bskpi_pipi_pdf_Tot",
                                'color'      : [43./255,131./255,186./255],#RooFit.kGray+3,
                                'fill'       : 1001,
                                'name'       : 'bspipi',
                                'plotName'   : '#it{B}^{0}_{#it{s}}#rightarrow#it{#pi}^{ +}#it{#pi}^{ #minus}'  },
                        'A' : { 'components' : "bkg_pipi_pdf_Tot,phys_pipi_pdf_Tot,bdkpi_pipi_pdf_Tot,bspipi_pdf_Tot,bdpipi_pdf_Tot,bskpi_pipi_pdf_Tot",
                                'color'      : RooFit.kBlack,
                                'fill'       : 0,
                                'name'       : 'total',
                                'plotName'   : '#it{B}^{0}#rightarrow#it{#pi}^{ +}#it{#pi}^{ #minus}' },

                        # 'E' : { 'components' : "phys_pipi_pdf_Tot",
                        #         'color'      : [215./255,25./255,28./255],#RooFit.kGray+1,
                        #         'fill'       : 1001,
                        #         'name'       : '3body',
                        #         'plotName'   : '3-Body bkg.' },
                        # 'D' : { 'components' : 'phys_pipi_pdf_Tot,bskpi_pipi_pdf_Tot',
                        #         'color'      : [1./255,254./255,254./255],#RooFit.kGray,
                        #         'fill'       : 1001,
                        #         'name'       : 'bskpi',
                        #         'plotName'   : '#it{B}^{0}_{#it{s}}#rightarrow#it{#pi}^{ +}#it{K}^{ #minus}'  },
                        # 'C' : { 'components' : "phys_pipi_pdf_Tot,bdkpi_pipi_pdf_Tot,bskpi_pipi_pdf_Tot",
                        #         'color'      : [253./255,174./255,97./255],#RooFit.kGray+2,
                        #         'fill'       : 1001,
                        #         'name'       : 'bdkpi',
                        #         'plotName'   : '#it{B}^{0}#rightarrow#it{K}^{ +}#it{#pi}^{ #minus}' },
                        # 'B' : { 'components' : "phys_pipi_pdf_Tot,bdkpi_pipi_pdf_Tot,bspipi_pdf_Tot,bskpi_pipi_pdf_Tot",
                        #         'color'      : [43./255,131./255,186./255],#RooFit.kGray+3,
                        #         'fill'       : 1001,
                        #         'name'       : 'bspipi',
                        #         'plotName'   : '#it{B}^{0}_{#it{s}}#rightarrow#it{#pi}^{ +}#it{#pi}^{ #minus}'  },
                        # 'A' : { 'components' : "phys_pipi_pdf_Tot,bdkpi_pipi_pdf_Tot,bspipi_pdf_Tot,bdpipi_pdf_Tot,bskpi_pipi_pdf_Tot",
                        #         'color'      : RooFit.kBlack,
                        #         'fill'       : 0,
                        #         'name'       : 'total',
                        #         'plotName'   : '#it{B}^{0}#rightarrow#it{#pi}^{ +}#it{#pi}^{ #minus}' },

    #                    'A' : { 'components' : "bkg_pipi_pdf_Tot,phys_pipi_pdf_Tot,bdkpi_pipi_pdf_Tot,bspipi_pdf_Tot,bdpipi_pdf_Tot",
     #                           'color'      : RooFit.kRed,
      #                          'fill'       : 0,
       #                         'name'       : 'total',
        #                        'plotName'   : '#it{B}^{0}#rightarrow#it{#pi}^{ +}#it{#pi}^{ #minus}' },
                    },
        "KK_Tot"   : { 
            'E' : { 'components' : 'bkg_kk_pdf_Tot',
                                       'color'      : [171./255,221./255,164./255],#RooFit.kGray,
                                       'fill'       : 1001,
                                       'name'       : 'bkg',
                                       'plotName'   : 'Comb. bkg.' },
                               'D' : { 'components' : 'bkg_kk_pdf_Tot,phys_kk_pdf_Tot',
                                       'color'      : [215./255,25./255,28./255],#RooFit.kGray+1,
                                       'fill'       : 1001,
                                       'name'       : '3body',
                                       'plotName'   : '3-Body bkg.' },
                               'C' : { 'components' : "bkg_kk_pdf_Tot,phys_kk_pdf_Tot,bdkk_pdf_Tot,lbpk_kk_pdf_Tot",
                                       'color'      : (253./255,174./255,97./255),#RooFit.kGray+2,
                                       'fill'       : 1001,
                                       'name'       : 'lbpk',
                                       'plotName'   : '#splitline{#Lambda^{0}_{#it{b}}#rightarrow#it{p}#it{K}^{ #minus},}{#it{B}^{0}#rightarrow#it{K}^{ +}#it{K}^{ #minus}}' },
                               'B' : { 'components' : "bkg_kk_pdf_Tot,phys_kk_pdf_Tot,bdkk_pdf_Tot,lbpk_kk_pdf_Tot,bdkpi_kk_pdf_Tot",
                                       'color'      : [43./255,131./255,186./255],#RooFit.kGray+3,
                                       'fill'       : 1001,
                                       'name'       : 'bdkpi',
                                       'plotName'   : '#it{B}^{0}#rightarrow#it{K}^{ +}#it{#pi}^{ #minus}' },
                               'A' : { 'components' : "bkg_kk_pdf_Tot,phys_kk_pdf_Tot,bdkk_pdf_Tot,lbpk_kk_pdf_Tot,bdkpi_kk_pdf_Tot,bskk_pdf_Tot",
                                       'color'      : RooFit.kBlack,
                                       'fill'       : 0,
                                       'name'       : 'total',
                                       'plotName'   : '#it{B}^{0}_{#it{s}}#rightarrow#it{K}^{ +}#it{K}^{ #minus}' },
                             },
}
