/********************************************************************
* readTreeDict.cxx.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error readTreeDict.cxx.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablereadTreeDictdOcxx();
extern void G__cpp_setup_inheritancereadTreeDictdOcxx();
extern void G__cpp_setup_typetablereadTreeDictdOcxx();
extern void G__cpp_setup_memvarreadTreeDictdOcxx();
extern void G__cpp_setup_globalreadTreeDictdOcxx();
extern void G__cpp_setup_memfuncreadTreeDictdOcxx();
extern void G__cpp_setup_funcreadTreeDictdOcxx();
extern void G__set_cpp_environmentreadTreeDictdOcxx();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "readTree.hxx"
#include "readMCTree.hxx"
#include "lifetime.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__readTreeDictdOcxxLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__readTreeDictdOcxxLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__readTreeDictdOcxxLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__readTreeDictdOcxxLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__readTreeDictdOcxxLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__readTreeDictdOcxxLN_TTree;
extern G__linked_taginfo G__readTreeDictdOcxxLN_TBranch;
extern G__linked_taginfo G__readTreeDictdOcxxLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__readTreeDictdOcxxLN_TEntryList;
extern G__linked_taginfo G__readTreeDictdOcxxLN_TNtuple;
extern G__linked_taginfo G__readTreeDictdOcxxLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__readTreeDictdOcxxLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__readTreeDictdOcxxLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__readTreeDictdOcxxLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__readTreeDictdOcxxLN_readTree;
extern G__linked_taginfo G__readTreeDictdOcxxLN_readMCTree;
extern G__linked_taginfo G__readTreeDictdOcxxLN_lifetime;
extern G__linked_taginfo G__readTreeDictdOcxxLN_maplEunsignedsPintcOlongcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOlonggRsPgRsPgR;

/* STUB derived class for protected member access */
