/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTIMEACCPDF
#define ROOTIMEACCPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooTimeAccPdf : public RooAbsPdf {
public:
  RooTimeAccPdf() {} ; 
  RooTimeAccPdf(const char *name, const char *title,
	      RooAbsReal& _time,
	      RooAbsReal& _p0,
	      RooAbsReal& _p1,
	      RooAbsReal& _p2,
	      RooAbsReal& _p3,
	      RooAbsReal& _p4,
	      RooAbsReal& _p5,
	      RooAbsReal& _p6,
	      RooAbsReal& _p7,
	      RooAbsReal& _p8,
	      RooAbsReal& _p9,
	      RooAbsReal& _p10);
  RooTimeAccPdf(const RooTimeAccPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTimeAccPdf(*this,newname); }
  inline virtual ~RooTimeAccPdf() { }

protected:

  RooRealProxy time ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  RooRealProxy p3 ;
  RooRealProxy p4 ;
  RooRealProxy p5 ;
  RooRealProxy p6 ;
  RooRealProxy p7 ;
  RooRealProxy p8 ;
  RooRealProxy p9 ;
  RooRealProxy p10 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooTimeAccPdf,1) // Your description goes here...
};
 
#endif
