/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTimeAccPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooTimeAccPdf) 

 RooTimeAccPdf::RooTimeAccPdf(const char *name, const char *title, 
                        RooAbsReal& _time,
                        RooAbsReal& _p0,RooAbsReal& _p1,RooAbsReal& _p2,
                        RooAbsReal& _p3,RooAbsReal& _p4,RooAbsReal& _p5,
                        RooAbsReal& _p6,RooAbsReal& _p7,RooAbsReal& _p8,
                        RooAbsReal& _p9,RooAbsReal& _p10):
   RooAbsPdf(name,title), 
   time("time","time",this,_time),
   p0("p0","p0",this,_p0),
   p1("p1","p1",this,_p1),
   p2("p2","p2",this,_p2),
   p3("p3","p3",this,_p3),
   p4("p4","p4",this,_p4),
   p5("p5","p5",this,_p5),
   p6("p6","p6",this,_p6),
   p7("p7","p7",this,_p7),
   p8("p8","p8",this,_p8),
   p9("p9","p9",this,_p9),
   p10("p10","p10",this,_p10) {

}


 RooTimeAccPdf::RooTimeAccPdf(const RooTimeAccPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   time("time",this,other.time),
   p0("p0",this,other.p0),
   p1("p1",this,other.p1),
   p2("p2",this,other.p2),
   p3("p3",this,other.p3),
   p4("p4",this,other.p4),
   p5("p5",this,other.p5),
   p6("p6",this,other.p6),
   p7("p7",this,other.p7),
   p8("p8",this,other.p8),
   p9("p9",this,other.p9),
   p10("p10",this,other.p10) { 
 } 



 Double_t RooTimeAccPdf::evaluate() const {

   Double_t retVal = 1 + p1*tanh(p2*(time-p3));
   
   retVal += p4*tanh(p5*(time-p6)    + 
                     p7*(time-p6)*(time-p6) + 
                     p8*(time-p6)*(time-p6)*(time-p6) );
   
   
   if(time > p10) {
     retVal = 1 + p1*tanh(p2*(p10-p3));
     retVal += p4*tanh(p5*(p10-p6)    +
                       p7*(p10-p6)*(p10-p6) +
                       p8*(p10-p6)*(p10-p6)*(p10-p6) );
     retVal *= (1+p9*(time-p10)*(time-p10));
   }
   
   retVal = p0*retVal;

   return max(0.00001,retVal);

 }



